import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import {ROOT,fingerprint,digest} from '../runner/files.mjs';
import {connect,createExecution,execution,record,updateExecution} from '../runner/store.mjs';
import {saveCheckpoint} from '../runner/checkpoints.mjs';
import {humanCheckpoint} from '../runner/catalog.mjs';
import {main as smokeCommand} from '../scripts/smoke.mjs';
import {reportScriptHash} from '../reports.mjs';
import {createHash} from 'node:crypto';

test('catalog integrity, frozen run definitions, durable edits and honest result recording',async()=>{
  const sourceBefore=(await fingerprint(ROOT)).sha256;
  const dir=mkdtempSync(path.join(tmpdir(),'wizard-smoke-check-'));
  let child,base;
  const start=async()=>{
    child=spawn(process.execPath,['server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:'0',SMOKE_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});
    base=await new Promise((resolve,reject)=>{let output='';child.stdout.on('data',d=>{output+=d;const match=output.match(/http:\/\/127\.0\.0\.1:\d+/);if(match)resolve(match[0]);});child.on('error',reject);child.on('exit',code=>reject(new Error(`Server exited ${code}: ${output}`)));});
  };
  const stop=async()=>{if(child&&child.exitCode===null){const closed=once(child,'exit');child.kill('SIGTERM');await closed;}};
  const request=async(route,method='GET',body,extra={})=>{const r=await fetch(base+'/api'+route,{method,headers:{'Content-Type':'application/json',...extra},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};
  try{
    await start();
    const setup=(await request('/run-setup')).data;
    assert.equal(setup.courses[0].id,'automated-full');assert.equal(setup.courses[0].checkCount,137);
    assert.deepEqual(setup.courses[0].targets,{packaged:57,desktop:73,service:7});
    assert.ok(setup.courses.every(c=>!c.checkpoint));assert.deepEqual(setup.runtimes,[]);
    assert.equal((await fetch(base+'/run-setup.js')).status,200);assert.equal((await fetch(base+'/wizard-tokens.css')).status,200);
    assert.deepEqual((await request('/runs')).data,[],'Opening run setup must not launch tests');
    const context=(await request('/checks/D-TRACK-ADD/context')).data;assert.equal(context.check.id,'D-TRACK-ADD');assert.equal(context.accepted,false);assert.match(context.prompt,/independent verification/);
    assert.equal((await request('/checks/A-CLI-01/context')).data.accepted,true);
    assert.equal((await request('/checks/unknown/context')).status,404);
    const pack=(await request('/checks/D-TRACK-ADD/context','POST',{})).data;assert.ok(pack.path.startsWith(realpathSync(dir)+'/agent-context/'));
    assert.deepEqual((await request('/runs')).data,[],'Context export must not launch or record a test');
    assert.equal(setup.defaultRuntimeId,'');
    const tools={app:'test-tools/Wizard.app',cli:'test-tools/wiz-cli',qtPlugin:'test-tools/libqcocoa.dylib',bridge:'test-tools/libwizard_smoke.dylib'};
    mkdirSync(path.join(dir,tools.app,'Contents/MacOS'),{recursive:true});
    for(const file of [tools.app+'/Contents/MacOS/wizard',tools.cli,tools.qtPlugin,tools.bridge])writeFileSync(path.join(dir,file),'Synthetic file; never executed');
    writeFileSync(path.join(dir,'desktop-runtime.json'),JSON.stringify(tools));
    const installed=(await request('/run-setup')).data;
    const agentSetup=await smokeCommand(['setup','--server',base]);assert.equal(agentSetup.result.defaultRuntimeId,installed.defaultRuntimeId);
    assert.equal(installed.runtimes[0].id,installed.defaultRuntimeId);
    assert.equal(installed.runtimes[0].runtime.app,realpathSync(path.join(dir,tools.app)));
    assert.equal(installed.runtimes[0].available,true);
    rmSync(path.join(dir,tools.bridge));
    assert.equal((await request('/run-setup')).data.defaultRuntimeId,'','Missing native tools must not be selected automatically');
    writeFileSync(path.join(dir,'desktop-runtime.json'),'invalid JSON');
    const invalid=(await request('/run-setup')).data;
    assert.equal(invalid.defaultRuntimeId,'');assert.match(invalid.runtimeSetupError,/configuration could not be read/);
    rmSync(path.join(dir,'desktop-runtime.json'));
    assert.deepEqual((await request('/runs')).data,[],'Automatic tool discovery must never start a test');

    const theme=await fetch(base+'/wizard-tokens.css');assert.equal(theme.status,200);assert.match(theme.headers.get('Content-Type'),/text\/css/);assert.match(await theme.text(),/--selection: #447ab0/);
    const absent=await request('/runner/preflight','POST',{});assert.equal(absent.data.ok,false);assert.match(absent.data.error,/Choose a build and test course/);
    assert.deepEqual((await request('/runs')).data,[],'Checking readiness must not start a course');
    const content={runnerHash:'old-runner'},planHash=digest(content);mkdirSync(path.join(dir,'plans'));
    writeFileSync(path.join(dir,'plans',planHash+'.json'),JSON.stringify({...content,planHash}));
    assert.equal((await request('/plans/'+planHash)).data.planHash,planHash);
    const selectedReadiness=await request('/runner/preflight','POST',{planHash});assert.equal(selectedReadiness.data.ok,false);assert.match(selectedReadiness.data.error,/Runner changed/,'Selected plan is checked without a global prepared.json');
    assert.match((await request('/runner/preflight','POST',{planHash:'../other'})).data.error,/Invalid prepared plan ID/);
    assert.match((await request('/runner')).data.preflight.error,/Choose a build and test course/,'Selected readiness must not overwrite the legacy readiness record');
    writeFileSync(path.join(dir,'plans',planHash+'.json'),JSON.stringify({runnerHash:'tampered',planHash}));
    assert.equal((await request('/plans/'+planHash)).status,409);
    assert.equal((await fetch(base+'/history')).status,404);
    writeFileSync(path.join(dir,'history.html'),'<h1>Retained history fixture</h1>');
    const history=await fetch(base+'/history');assert.equal(history.status,200);assert.match(history.headers.get('Content-Security-Policy'),/sandbox/);
    assert.match(await history.text(),/Retained history fixture/);assert.equal((await fetch(base+'/history',{method:'POST'})).status,405);
    const {data:catalog}=await request('/catalog');
    assert.equal(catalog.tests.length,275);
    assert.equal(catalog.checkpoint.rows.length,137);
    assert.equal(catalog.tests.filter(t=>t.course==='Local desktop').length,78);
    assert.equal(catalog.tests.filter(t=>t.course==='Local services').length,8);
    assert.equal((await request('/desktop')).data.serviceCourse.cases.length,8);
    assert.ok(catalog.checkpoint.rows.find(r=>r.id==='EX-02').checks.some(c=>c.id==='S-EXPORT-UNSET-RATE'));
    assert.ok(catalog.checkpoint.rows.find(r=>r.id==='TL-02').checks.some(c=>c.id==='D-EDIT-SPLIT-REDO'));
    assert.deepEqual((await request('/desktop')).data.runs,[]);
    const tower = await request('/tower');
    assert.equal(tower.status,200);
    assert.equal(tower.data.format,'wizard-smoke-tower/v1');
    assert.equal(tower.data.historyUrl,'/history');
    assert.equal(tower.data.checks.length,143);
    assert.deepEqual(tower.data.runs,[]);
    assert.equal(tower.data.runner.prepared,false);
    assert.equal((await request('/desktop/start','POST',{kind:'handoff',sourceRun:'../../other',caseId:'D-TRACK-ADD'})).status,409);
    assert.equal(new Set(catalog.checkpoint.rows.map(r=>r.id)).size,137);
    assert.equal(catalog.checkpoint.comparison,undefined);
    assert.ok(catalog.checkpoint.rows.every(r=>r.sourceResults===undefined&&r.sourceOverall===undefined&&r.sourceNotes===undefined));
    assert.ok(catalog.tests.every(t=>t.sourceResults==null));
    assert.equal(catalog.checkpoint.rows.find(r=>r.id==='RG-03').sourceIssue,'WIZ-475');
    assert.ok(catalog.checkpoint.rows.every(r=>r.remaining&&r.nextAdapter));
    assert.ok(catalog.checkpoint.rows.filter(r=>r.environment==='NAS').every(r=>r.coverage==='Deferred'&&r.checks.length===0));
    assert.equal(new Set(catalog.tests.map(t=>t.id)).size,275);
    assert.equal(catalog.tests.filter(t=>t.kind==='Automated counterpart').length,133);
    assert.equal(catalog.tests.filter(t=>t.course==='First automated').length,71);
    assert.equal(catalog.tests.filter(t=>t.readiness==='Ready').length,0);
    assert.deepEqual((await request('/runs')).data,[],'imported source Pass must not create passing runs');
    for(const t of catalog.tests){assert.ok(t.fixtureIds.every(id=>catalog.gp.components.some(c=>c.id===id)));if(t.kind==='Automated counterpart')assert.ok(catalog.tests.some(p=>p.id===t.sourceId));}
    assert.equal((await request('/runs','POST',{name:'Missing build',operator:'Test',course:'First automated'})).status,400);
    const {data:run,status}=await request('/runs','POST',{name:'Integration check',build:'test-package@abc123',operator:'Integration test',course:'First automated'});
    assert.equal(status,201);assert.equal(run.results.length,71);assert.ok(run.results.every(r=>r.status==='Not run'));
    const target=catalog.tests.find(t=>t.id==='LP-02');
    const changed=await request('/tests/LP-02','PATCH',{revision:target.revision,title:'Updated project lifecycle',notes:'Saved across restart'});
    assert.equal(changed.status,200);assert.equal(changed.data.revision,target.revision+1);
    assert.equal((await request('/tests/LP-02','PATCH',{revision:target.revision,title:'Stale overwrite'})).status,409);
    assert.equal((await request('/tests/LP-02','PATCH',{revision:changed.data.revision,execution:'Human'})).status,400);
    assert.equal((await request('/tests/LP-02','PATCH',{revision:changed.data.revision,title:'Cross-site attempt'},{Origin:'https://example.invalid'})).status,403);
    const resultPath=`/runs/${run.id}/results/LP-02`;
    assert.equal((await request(resultPath,'PATCH',{revision:1,status:'Pass',note:'',recordedBy:'Test'})).status,400);
    const updated=await request(resultPath,'PATCH',{revision:1,status:'Blocked',note:'Fixture not created yet',recordedBy:'Test',evidence:'local/test-evidence.txt'});
    assert.equal(updated.status,200);
    const result=updated.data.results.find(r=>r.test_id==='LP-02');
    assert.equal(result.status,'Blocked');assert.equal(result.snapshot.title,target.title);assert.equal(result.snapshot.revision,target.revision);
    assert.equal((await request(resultPath,'PATCH',{revision:1,status:'Pass',note:'Stale status',recordedBy:'Test'})).status,409);
    const added=await request('/tests','POST',{title:'A new team test',area:'Timeline editing',expected:'A concrete expected result'});
    assert.equal(added.status,201);assert.equal(added.data.id,'CT-001');assert.equal(added.data.course,'Backlog');
    await stop();await start();
    const reopened=(await request('/catalog')).data;
    assert.equal(reopened.tests.find(t=>t.id==='LP-02').notes,'Saved across restart');assert.equal(reopened.tests.length,276);
    const persisted=(await request('/runs')).data[0];assert.equal(persisted.results.find(r=>r.test_id==='LP-02').status,'Blocked');
    const backup=(await request('/export')).data;assert.equal(backup.tests.length,276);assert.equal(backup.runs.length,1);
    const exported=await request('/exports','POST',{format:'csv',ids:['LP-02','CT-001']});assert.equal(exported.status,201);
    const csv=await (await fetch(base+exported.data.url)).text();assert.ok(csv.includes('Updated project lifecycle'));assert.ok(csv.includes('A new team test'));assert.ok(!csv.includes('A-TL-01'));
    const exportedJSON=await request('/exports','POST',{format:'json'});assert.equal(exportedJSON.status,201);assert.equal((await(await fetch(base+exportedJSON.data.url)).json()).runs.length,1);
    assert.equal((await request('/runner/start','POST',{planHash:'unprepared'})).status,409);
    assert.equal((await request('/runs')).data.length,1,'an unprepared start must not create an execution');
    const db=connect(dir);
    try{
      const plan={version:'test-only',packageHash:'a'.repeat(64),fixtureHash:'b'.repeat(64),planHash:'c'.repeat(64)};
      const id=createExecution(db,plan,dir,'Runner contract test','recovered-start-request');
      assert.throws(()=>createExecution(db,plan,dir),/already active/);
      assert.equal((await request(`/runs/${id}/results/A-CLI-01`,'PATCH',{revision:1,status:'Pass',note:'An attempted manual overwrite',recordedBy:'Test'})).status,409);
      const snapshot=db.prepare('SELECT snapshot FROM results WHERE run_id=? AND test_id=?').get(id,'A-CLI-01').snapshot;
      const current=JSON.parse(db.prepare('SELECT definition FROM tests WHERE id=?').get('A-CLI-01').definition);
      db.prepare('UPDATE tests SET definition=? WHERE id=?').run(JSON.stringify({...current,expected:'A changed contract'}),'A-CLI-01');
      record(db,id,'A-CLI-01','Running','Simulated interrupted runner','test-evidence');
      const interruptedTower=(await request('/tower')).data;
      assert.equal(interruptedTower.active,false,'Tower must reconcile a stopped worker without visiting the runner route');
      assert.equal(execution(db,id).state,'Unknown');
      const replay=await request('/runner/start','POST',{planHash:plan.planHash,operator:'Runner contract test',requestId:'recovered-start-request'});assert.equal(replay.status,200);assert.equal(replay.data.runId,id);assert.equal(replay.data.reused,true);
      assert.equal((await request('/requests/recovered-start-request')).data.id,id);
      assert.equal((await request('/runner/start','POST',{planHash:'other',operator:'Runner contract test',requestId:'recovered-start-request'})).status,409);
      const localReport=await request(`/runs/${id}/report`,'POST',{});assert.equal(localReport.status,201);assert.equal(localReport.data.evidenceStatus,'Gaps found');
      const reportResponse=await fetch(base+localReport.data.url);assert.equal(reportResponse.status,200);assert.ok((await reportResponse.text()).includes('Evidence needs attention'));
      const policy=reportResponse.headers.get('Content-Security-Policy');assert.ok(policy.includes("script-src 'sha256-"+reportScriptHash+"'"));assert.ok(policy.includes('sandbox allow-scripts'));assert.ok(!policy.includes('allow-same-origin'));
      const oldName='smoke-report-'+id+'-0123456789ab',oldRoot=path.join(dir,'exports',oldName),oldScript="document.title='retained report controls';";
      mkdirSync(oldRoot);writeFileSync(path.join(oldRoot,'index.html'),'<script>'+oldScript+'</script>');
      const oldResponse=await fetch(base+'/exports/'+oldName+'/index.html');assert.equal(oldResponse.status,200);assert.ok(oldResponse.headers.get('Content-Security-Policy').includes(createHash('sha256').update(oldScript).digest('base64')),'Historical reports retain permission for their exact original control script');
      assert.equal((await request(`/runs/${id}/report`,'POST',{})).data.path,localReport.data.path);
      const recovered=(await request('/runs')).data.find(r=>r.id===id);
      assert.equal(recovered.results.find(r=>r.test_id==='A-CLI-01').status,'Unknown');
      assert.ok(recovered.results.filter(r=>r.test_id!=='A-CLI-01').every(r=>r.status==='Blocked'));
      assert.equal(JSON.stringify(recovered.results.find(r=>r.test_id==='A-CLI-01').snapshot),snapshot);
      assert.throws(()=>createExecution(db,plan,dir),/differs from its mapped executable contract/);
      assert.equal(db.prepare('SELECT COUNT(*) AS n FROM executions').get().n,1);
      mkdirSync(execution(db,id).artifact_root,{recursive:true});
      const checkpoint=saveCheckpoint(db,id,{state:'Waiting',definition:humanCheckpoint,observations:[],requests:[],diagnostics:[],prompt:'Synthetic integration fixture; no Wizard session.'});
      updateExecution(db,id,'Waiting for human','Synthetic checkpoint fixture');
      assert.equal((await request('/checkpoints')).data.checkpoints[0].runId,id);
      assert.equal((await request(`/runs/${id}/checkpoint/resume`,'POST',{revision:checkpoint.revision,requestId:'no-human'})).status,409);
      const finding={revision:checkpoint.revision,requestId:'synthetic-human',operator:'Integration fixture',outcome:'Blocked',note:'Synthetic UI/service fixture; no human acceptance',handsOnSeconds:0,recordedVia:'human'};
      assert.equal((await request(`/runs/${id}/checkpoint/observe`,'POST',finding)).status,200);
      await stop();await start();
      const waiting=(await request(`/runs/${id}`)).data;
      assert.equal(waiting.execution.state,'Waiting for human');assert.equal(waiting.checkpoint.observations.length,1);
      const projected=(await request('/tower')).data.runs.find(r=>r.id===id);
      assert.equal(projected.state,'Waiting for human');assert.deepEqual(projected.checkpoint,{state:'Waiting',url:'/#run/'+id});
      assert.equal((await request(`/runs/${id}/checkpoint/observe`,'POST',finding)).data.reused,true);
      assert.equal((await request(`/runs/${id}/checkpoint/resume`,'POST',{revision:waiting.checkpoint.revision,requestId:'blocked-human'})).status,409);
      assert.equal((await request(`/runs/${id}/checkpoint/observe`,'POST',{...finding,requestId:'stale-revision'})).status,409);
    }finally{db.close();}
  }finally{await stop();rmSync(dir,{recursive:true,force:true});}
  assert.equal((await fingerprint(ROOT)).sha256,sourceBefore,'Catalog, run recording, reports and exports must leave source untouched');
});
