import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import {ROOT,fingerprint} from '../runner/files.mjs';
import {connect,createExecution,execution,record} from '../runner/store.mjs';

test('catalog integrity, frozen run definitions, durable edits and honest result recording',async()=>{
  const sourceBefore=(await fingerprint(ROOT)).sha256;
  const dir=mkdtempSync(path.join(tmpdir(),'wizard-smoke-check-'));
  let child,base;
  const start=async()=>{
    child=spawn(process.execPath,['server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:'0',SMOKE_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});
    base=await new Promise((resolve,reject)=>{let output='';child.stdout.on('data',d=>{output+=d;const match=output.match(/http:\/\/127\.0\.0\.1:\d+/);if(match)resolve(match[0]);});child.on('error',reject);child.on('exit',code=>reject(new Error(`Server exited ${code}: ${output}`)));});
  };
  const stop=async()=>{if(child&&child.exitCode===null){const closed=once(child,'exit');child.kill('SIGTERM');await closed;}};
  const request=async(route,method='GET',body,extra={})=>{const r=await fetch(base+'/api'+route,{method,headers:{'Content-Type':'application/json',...extra},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};
  try{
    await start();
    const {data:catalog}=await request('/catalog');
    assert.equal(catalog.tests.length,275);
    assert.equal(catalog.checkpoint.rows.length,137);
    assert.equal(catalog.tests.filter(t=>t.course==='Local desktop').length,77);
    assert.equal(catalog.tests.filter(t=>t.course==='Local services').length,9);
    assert.equal((await request('/desktop')).data.serviceCourse.cases.length,9);
    assert.ok(catalog.checkpoint.rows.find(r=>r.id==='EX-02').checks.some(c=>c.id==='S-EXPORT-UNSET-RATE'));
    assert.ok(catalog.checkpoint.rows.find(r=>r.id==='TL-02').checks.some(c=>c.id==='D-EDIT-SPLIT-REDO'));
    assert.deepEqual((await request('/desktop')).data.runs,[]);
    const tower = await request('/tower');
    assert.equal(tower.status,200);
    assert.equal(tower.data.format,'wizard-smoke-tower/v1');
    assert.equal(tower.data.checks.length,143);
    assert.deepEqual(tower.data.runs,[]);
    assert.equal(tower.data.runner.prepared,false);
    assert.equal((await request('/desktop/start','POST',{kind:'handoff',sourceRun:'../../other',caseId:'D-TRACK-ADD'})).status,409);
    assert.equal(new Set(catalog.checkpoint.rows.map(r=>r.id)).size,137);
    assert.equal(catalog.checkpoint.comparison,undefined);
    assert.ok(catalog.checkpoint.rows.every(r=>r.sourceResults===undefined&&r.sourceOverall===undefined&&r.sourceNotes===undefined));
    assert.ok(catalog.tests.every(t=>t.sourceResults==null));
    assert.equal(catalog.checkpoint.rows.find(r=>r.id==='RG-03').sourceIssue,'WIZ-475');
    assert.ok(catalog.checkpoint.rows.every(r=>r.remaining&&r.nextAdapter));
    assert.ok(catalog.checkpoint.rows.filter(r=>r.environment==='NAS').every(r=>r.coverage==='Deferred'&&r.checks.length===0));
    assert.equal(new Set(catalog.tests.map(t=>t.id)).size,275);
    assert.equal(catalog.tests.filter(t=>t.kind==='Automated counterpart').length,133);
    assert.equal(catalog.tests.filter(t=>t.course==='First automated').length,71);
    assert.equal(catalog.tests.filter(t=>t.readiness==='Ready').length,0);
    assert.deepEqual((await request('/runs')).data,[],'imported source Pass must not create passing runs');
    for(const t of catalog.tests){assert.ok(t.fixtureIds.every(id=>catalog.gp.components.some(c=>c.id===id)));if(t.kind==='Automated counterpart')assert.ok(catalog.tests.some(p=>p.id===t.sourceId));}
    assert.equal((await request('/runs','POST',{name:'Missing build',operator:'Test',course:'First automated'})).status,400);
    const {data:run,status}=await request('/runs','POST',{name:'Integration check',build:'test-package@abc123',operator:'Integration test',course:'First automated'});
    assert.equal(status,201);assert.equal(run.results.length,71);assert.ok(run.results.every(r=>r.status==='Not run'));
    const target=catalog.tests.find(t=>t.id==='LP-02');
    const changed=await request('/tests/LP-02','PATCH',{revision:target.revision,title:'Updated project lifecycle',notes:'Saved across restart'});
    assert.equal(changed.status,200);assert.equal(changed.data.revision,target.revision+1);
    assert.equal((await request('/tests/LP-02','PATCH',{revision:target.revision,title:'Stale overwrite'})).status,409);
    assert.equal((await request('/tests/LP-02','PATCH',{revision:changed.data.revision,execution:'Human'})).status,400);
    assert.equal((await request('/tests/LP-02','PATCH',{revision:changed.data.revision,title:'Cross-site attempt'},{Origin:'https://example.invalid'})).status,403);
    const resultPath=`/runs/${run.id}/results/LP-02`;
    assert.equal((await request(resultPath,'PATCH',{revision:1,status:'Pass',note:'',recordedBy:'Test'})).status,400);
    const updated=await request(resultPath,'PATCH',{revision:1,status:'Blocked',note:'Fixture not created yet',recordedBy:'Test',evidence:'local/test-evidence.txt'});
    assert.equal(updated.status,200);
    const result=updated.data.results.find(r=>r.test_id==='LP-02');
    assert.equal(result.status,'Blocked');assert.equal(result.snapshot.title,target.title);assert.equal(result.snapshot.revision,target.revision);
    assert.equal((await request(resultPath,'PATCH',{revision:1,status:'Pass',note:'Stale status',recordedBy:'Test'})).status,409);
    const added=await request('/tests','POST',{title:'A new team test',area:'Timeline editing',expected:'A concrete expected result'});
    assert.equal(added.status,201);assert.equal(added.data.id,'CT-001');assert.equal(added.data.course,'Backlog');
    await stop();await start();
    const reopened=(await request('/catalog')).data;
    assert.equal(reopened.tests.find(t=>t.id==='LP-02').notes,'Saved across restart');assert.equal(reopened.tests.length,276);
    const persisted=(await request('/runs')).data[0];assert.equal(persisted.results.find(r=>r.test_id==='LP-02').status,'Blocked');
    const backup=(await request('/export')).data;assert.equal(backup.tests.length,276);assert.equal(backup.runs.length,1);
    const exported=await request('/exports','POST',{format:'csv',ids:['LP-02','CT-001']});assert.equal(exported.status,201);
    const csv=await (await fetch(base+exported.data.url)).text();assert.ok(csv.includes('Updated project lifecycle'));assert.ok(csv.includes('A new team test'));assert.ok(!csv.includes('A-TL-01'));
    const exportedJSON=await request('/exports','POST',{format:'json'});assert.equal(exportedJSON.status,201);assert.equal((await(await fetch(base+exportedJSON.data.url)).json()).runs.length,1);
    assert.equal((await request('/runner/start','POST',{planHash:'unprepared'})).status,409);
    assert.equal((await request('/runs')).data.length,1,'an unprepared start must not create an execution');
    const db=connect(dir);
    try{
      const plan={version:'test-only',packageHash:'a'.repeat(64),fixtureHash:'b'.repeat(64),planHash:'c'.repeat(64)};
      const id=createExecution(db,plan,dir,'Runner contract test','recovered-start-request');
      assert.throws(()=>createExecution(db,plan,dir),/already active/);
      assert.equal((await request(`/runs/${id}/results/A-CLI-01`,'PATCH',{revision:1,status:'Pass',note:'An attempted manual overwrite',recordedBy:'Test'})).status,409);
      const snapshot=db.prepare('SELECT snapshot FROM results WHERE run_id=? AND test_id=?').get(id,'A-CLI-01').snapshot;
      const current=JSON.parse(db.prepare('SELECT definition FROM tests WHERE id=?').get('A-CLI-01').definition);
      db.prepare('UPDATE tests SET definition=? WHERE id=?').run(JSON.stringify({...current,expected:'A changed contract'}),'A-CLI-01');
      record(db,id,'A-CLI-01','Running','Simulated interrupted runner','test-evidence');
      const interruptedTower=(await request('/tower')).data;
      assert.equal(interruptedTower.active,false,'Tower must reconcile a stopped worker without visiting the runner route');
      assert.equal(execution(db,id).state,'Unknown');
      const replay=await request('/runner/start','POST',{planHash:plan.planHash,operator:'Runner contract test',requestId:'recovered-start-request'});assert.equal(replay.status,200);assert.equal(replay.data.runId,id);assert.equal(replay.data.reused,true);
      assert.equal((await request('/requests/recovered-start-request')).data.id,id);
      assert.equal((await request('/runner/start','POST',{planHash:'other',operator:'Runner contract test',requestId:'recovered-start-request'})).status,409);
      const localReport=await request(`/runs/${id}/report`,'POST',{});assert.equal(localReport.status,201);assert.equal(localReport.data.evidenceStatus,'Gaps found');
      const reportResponse=await fetch(base+localReport.data.url);assert.equal(reportResponse.status,200);assert.ok((await reportResponse.text()).includes('V1 acceptance'));
      assert.equal((await request(`/runs/${id}/report`,'POST',{})).data.path,localReport.data.path);
      const recovered=(await request('/runs')).data.find(r=>r.id===id);
      assert.equal(recovered.results.find(r=>r.test_id==='A-CLI-01').status,'Unknown');
      assert.ok(recovered.results.filter(r=>r.test_id!=='A-CLI-01').every(r=>r.status==='Blocked'));
      assert.equal(JSON.stringify(recovered.results.find(r=>r.test_id==='A-CLI-01').snapshot),snapshot);
      assert.throws(()=>createExecution(db,plan,dir),/differs from its mapped executable contract/);
      assert.equal(db.prepare('SELECT COUNT(*) AS n FROM executions').get().n,1);
    }finally{db.close();}
  }finally{await stop();rmSync(dir,{recursive:true,force:true});}
  assert.equal((await fingerprint(ROOT)).sha256,sourceBefore,'Catalog, run recording, reports and exports must leave source untouched');
});
