import {beginCheck,endCheck,requireOrdinaryTimingFixture,requireValidSourceTiming} from './check-support.mjs';
import path from 'node:path';
import {stat} from 'node:fs/promises';
import {setExportOutput} from './export-dialog.mjs';
import {nativeCall,desktopCall} from './adapter.mjs';
import {readJSON,writeJSON} from '../runner/files.mjs';
import {assert,pause,same,snapshotState,clips} from '../runner/engine.mjs';
const file=process.argv[2],s=await readJSON(file),report={scope:s.scope,pid:s.pid,generation:s.generation,results:[]};
const n=(op,p)=>nativeCall(file,op,p),c=(op,p)=>desktopCall(file,op,p),ui=()=>n('inspect'),timeline=()=>c('timeline.inspect',{timeline_id:s.main.id});
async function until(fn){for(let i=0;i<50;i++){const v=await fn();if(v)return v;await pause(100);}throw Error('Expected GUI outcome did not arrive within five seconds');}
async function check(id,fn){if(!await beginCheck(file,id))return;const baseline=snapshotState(await timeline());try{report.results.push({id,status:'Pass',evidence:await fn()});}catch(e){report.results.push({id,status:e.status||'Fail',error:e.message});if(e.status==='Unknown'){await writeJSON(path.join(s.root,'desktop-paths-report.json'),report);await endCheck(file,report.results.at(-1));throw e;}}try{same(snapshotState(await timeline()),baseline,'Check must restore timeline before continuing');}catch(e){Object.assign(report.results.at(-1),{status:'Fail',restoreError:e.message,error:(report.results.at(-1).error||'')+'; '+e.message});await writeJSON(path.join(s.root,'desktop-paths-report.json'),report);await endCheck(file,report.results.at(-1));throw e;}await writeJSON(path.join(s.root,'desktop-paths-report.json'),report);await endCheck(file,report.results.at(-1));}
async function focus(){const u=await ui();await n('activate',{target:u.widgets.find(w=>w.class==='MainWindow').id});await until(async()=>(await ui()).widgets.some(w=>w.class==='MainWindow'&&w.active));return u.widgets.filter(w=>w.class==='TimelineWidget').sort((a,b)=>a.y-b.y)[0];}
const key=(v,key)=>n('key',{target:v.id,key});
const names=v=>v.model.map(r=>r[0]).sort();
const media=u=>u.widgets.find(w=>w.class==='QTreeView');
async function selectFirst(){await c('render.bind_timeline',{timeline_id:s.main.id,playhead_frame:0});const v=await focus();await key(v,'V');await n('click',{target:v.id,x:25,y:115});return v;}
async function undo(v,before,save=false){await key(v,'Ctrl+Z');if(save){await pause(100);const a=(await ui()).actions.find(a=>a.text==='Save'&&a.enabled);await n('action',{target:a.id});}return until(async()=>{const a=await timeline();return JSON.stringify(snapshotState(a))===JSON.stringify(snapshotState(before))?a:null;});}
await check('D-MEDIA-VIEWS',async()=>{let u=await ui();const before=names(media(u));assert(before.includes('pattern_24.mov')&&before.includes('motion_25.mp4'),'GP media missing');await n('click',{target:u.widgets.find(w=>w.tooltip==='Grid view').id});u=await until(async()=>{const a=await ui();return a.widgets.some(w=>w.class==='QListView')?a:null;});same(names(u.widgets.find(w=>w.class==='QListView')),before,'Grid media');assert(u.widgets.find(w=>w.tooltip==='Grid view').checked,'Grid button not selected');await n('click',{target:u.widgets.find(w=>w.tooltip==='List view').id});u=await until(async()=>{const a=await ui();return media(a)?a:null;});same(names(media(u)),before,'List media');return {items:before,views:['grid','list']};});
await check('D-MEDIA-OPEN',async()=>{let u=await ui(),v=media(u),row=v.model.findIndex(r=>r[0]==='pattern_24.mov');await n('item-click',{target:v.id,row});await until(async()=>media(await ui()).selectedRows.includes(row));await n('item-click',{target:v.id,row,double:true});u=await until(async()=>{const a=await ui();return a.widgets.some(w=>w.name==='previewSourceLabel'&&w.text==='pattern_24.mov')?a:null;});assert(u.widgets.find(w=>w.name==='previewSegmentDuration').text==='00:00:12:00','Wrong source duration');return {selectedRow:row,source:'pattern_24.mov',duration:'00:00:12:00'};});
await check('D-MEDIA-TIMELINE',async()=>{let u=await ui(),v=media(u),row=v.model.findIndex(r=>r[0]==='Secondary');await n('item-click',{target:v.id,row,double:true});await until(async()=>{const a=await ui();return a.widgets.some(w=>w.name==='panelSubtabSelector'&&w.text.startsWith('Secondary'));});u=await ui();v=media(u);const main=(await timeline()).timeline.name;await n('item-click',{target:v.id,row:v.model.findIndex(r=>r[0]===main),double:true});await until(async()=>(await ui()).widgets.some(w=>w.name==='panelSubtabSelector'&&w.text.startsWith(main)));return {opened:['Secondary',main]};});
await check('D-TRANSPORT-KEYS',async()=>{const v=await selectFirst();await c('playback.seek',{time:1});await key(v,'Right');await until(async()=>(await c('playback.query_transport')).frame===25);await key(v,'Left');await until(async()=>(await c('playback.query_transport')).frame===24);await key(v,'Space');await pause(400);const playing=await c('playback.query_transport');await key(v,'Space');const stopped=await until(async()=>{const q=await c('playback.query_transport');return !q.playing?q:null;});await pause(200);const settled=await c('playback.query_transport');assert(playing.playing&&playing.frame>24,'Keyboard playback did not advance');assert(stopped.frame===settled.frame,'Keyboard pause drifted');return {stepForward:25,stepBack:24,playing,stopped};});
await check('D-TIMELINE-TOOLS',async()=>{const v=await focus();for(const [k,text] of [['C','Cut'],['T','Slip'],['F','Anchor'],['V','Select']]){await key(v,k);await until(async()=>(await ui()).widgets.some(w=>w.name==='panelChromeAction'&&w.text===text&&w.checked));}const snap=(await ui()).widgets.find(w=>w.text==='Snapping').checked;await key(v,'S');await until(async()=>(await ui()).widgets.find(w=>w.text==='Snapping').checked!==snap);await key(v,'S');await until(async()=>(await ui()).widgets.find(w=>w.text==='Snapping').checked===snap);return {tools:['Cut','Slip','Anchor','Select'],snappingRestored:snap};});
await check('D-EDIT-SPLIT-REDO',async()=>{const v=await selectFirst(),before=await timeline();await writeJSON(path.join(s.root,'split-baseline.json'),before);requireOrdinaryTimingFixture(before,s.clip);await c('playback.seek',{time:2});await key(v,'B');const split=await until(async()=>{const a=await timeline();return clips(a).length===clips(before).length+1?a:null;});await writeJSON(path.join(s.root,'split-observed.json'),split);await writeJSON(path.join(s.root,'split-undo.json'),await undo(v,before));await key(v,'Ctrl+Shift+Z');const redo=await until(async()=>{const a=await timeline();return clips(a).length===clips(split).length?a:null;});await writeJSON(path.join(s.root,'split-redo.json'),redo);await writeJSON(path.join(s.root,'split-redo-undo.json'),await undo(v,before));same(snapshotState(redo),snapshotState(split),'Redo split');const parts=clips(split).filter(c=>c.source.asset_id===clips(before)[0].source.asset_id).sort((a,b)=>a.timeline_range.start_seconds-b.timeline_range.start_seconds);same(parts.map(c=>c.timeline_range),[{start_seconds:0,end_seconds:2},{start_seconds:2,end_seconds:4}],'Split placement');same(parts.map(c=>c.source.source_range),[{start_seconds:1,end_seconds:3},{start_seconds:3,end_seconds:5}],'Split source bounds');for(const part of parts)requireValidSourceTiming(part.source);return {parts,undo:true,redo:true};});
await check('D-EDIT-DELETE',async()=>{const v=await selectFirst(),before=await timeline();await key(v,'Backspace');const after=await until(async()=>{const a=await timeline();return clips(a).length===clips(before).length-1?a:null;});await undo(v,before);assert(!clips(after).some(c=>c.clip_id===s.clip),'Delete removed wrong clip');same(clips(after).find(c=>c.clip_id===clips(before)[1].clip_id).timeline_range,clips(before)[1].timeline_range,'Delete preserves other placement');return {removed:s.clip,undoRestored:true};});
await check('D-EDIT-DISABLE',async()=>{const v=await selectFirst(),before=await timeline();await key(v,'D');const after=await until(async()=>{const a=await timeline();return clips(a).find(c=>c.clip_id===s.clip).enabled===false?a:null;});await undo(v,before);return {clip:s.clip,disabled:!clips(after).find(c=>c.clip_id===s.clip).enabled,undoRestored:true};});
await check('D-EDIT-NUDGE',async()=>{const v=await selectFirst(),before=await timeline();await key(v,'.');const after=await until(async()=>{const a=await timeline();return clips(a).find(c=>c.clip_id===s.clip).timeline_range.start_seconds>0?a:null;});await undo(v,before);const moved=clips(after).find(c=>c.clip_id===s.clip);assert(Math.abs(moved.timeline_range.start_seconds-1/24)<1e-8,'Nudge did not move exactly one frame');same(moved.source,clips(before)[0].source,'Nudge source');return {range:moved.timeline_range,undoRestored:true};});
await check('D-EDIT-DRAG',async()=>{const v=await selectFirst(),before=await timeline();await n('drag',{target:v.id,x:25,y:115,toX:41,toY:115});const after=await until(async()=>{const a=await timeline();return clips(a)[0].timeline_range.start_seconds>0?a:null;});await undo(v,before);const moved=clips(after).find(c=>c.clip_id===s.clip),r=moved.timeline_range;assert(r.start_seconds>0&&r.start_seconds<2&&Math.abs(r.end_seconds-r.start_seconds-4)<1e-8,'Drag must move inside the gap without changing duration');assert(Math.abs(r.start_seconds*24-Math.round(r.start_seconds*24))<1e-8,'Drag placement is not on a frame');same(moved.source,clips(before)[0].source,'Drag preserves source');same(clips(after)[1],clips(before)[1],'Drag preserves neighbor');return {range:r,sourceUnchanged:true,undoRestored:true};});
await check('D-EDIT-TRIM',async()=>{const v=await selectFirst(),before=await timeline();await writeJSON(path.join(s.root,'trim-baseline.json'),before);requireOrdinaryTimingFixture(before,s.clip);await n('drag',{target:v.id,x:63,y:115,toX:47,toY:115});const after=await until(async()=>{const a=await timeline();return clips(a)[0].timeline_range.end_seconds<4?a:null;});await writeJSON(path.join(s.root,'trim-observed.json'),after);await writeJSON(path.join(s.root,'trim-undo.json'),await undo(v,before));const trimmed=clips(after)[0],r=trimmed.timeline_range,source=trimmed.source;assert(r.start_seconds===0&&r.end_seconds>2&&r.end_seconds<4,'Right trim changed wrong edge');assert(source.source_range.start_seconds===1&&Math.abs(source.source_range.end_seconds-1-r.end_seconds)<1e-8,'Trim source and timeline durations disagree');same(clips(after)[1],clips(before)[1],'Trim preserves neighbor');requireValidSourceTiming(source);return {range:r,source:source.source_range,undoRestored:true};});
await check('D-TRACK-ADD',async()=>{for(const [label,address] of [['+ Video','V2'],['+ Audio','A2']]){await focus();const before=await timeline(),u=await ui();await n('click',{target:u.widgets.find(w=>w.name==='panelChromeAction'&&w.text===label).id});await writeJSON(path.join(s.root,'track-'+address+'-before-save-ui.json'),await ui());const save=(await ui()).actions.find(a=>a.text==='Save'&&a.enabled);await n('action',{target:save.id});let after;try{after=await until(async()=>{const a=await timeline();return a.tracks.length===before.tracks.length+1?a:null;});}finally{await writeJSON(path.join(s.root,'track-'+address+'-observed.json'),{ui:await ui(),timeline:await timeline()});}const v=await focus();await undo(v,before,true);const added=after.tracks.filter(t=>!before.tracks.some(b=>b.track_id===t.track_id));assert(added.length===1&&added[0].address===address&&!added[0].items.some(i=>i.kind==='clip'),'Added track has wrong type or content');}return {added:['video','audio'],undoRestored:true};});
await check('D-PROJECT-CANCEL-CLOSE',async()=>{const before=await timeline(),name='Unsaved smoke '+Date.now();await c('timeline.update',{id:'dirty-'+Date.now(),timeline_id:s.main.id,changes:{name}});const dirty=await timeline();let u=await ui();await n('close-window',{target:u.widgets.find(w=>w.class==='MainWindow').id});u=await until(async()=>{const a=await ui();return a.widgets.some(w=>w.class==='QMessageBox')?a:null;});const box=u.widgets.find(w=>w.class==='QMessageBox'),buttons=u.widgets.filter(w=>w.window===box.id&&w.class==='QPushButton').map(w=>w.text);await writeJSON(path.join(s.root,'unsaved-dialog.json'),u);await n('click',{target:u.widgets.find(w=>w.window===box.id&&w.text==='Cancel').id});await until(async()=>!(await ui()).widgets.some(w=>w.class==='QMessageBox'));const retained=await timeline();await c('timeline.update',{id:'restore-'+Date.now(),timeline_id:s.main.id,changes:{name:before.timeline.name}});await until(async()=>names(media(await ui())).includes(before.timeline.name));same(snapshotState(retained),snapshotState(dirty),'Cancel retains unsaved edit');assert(buttons.includes('Save')&&buttons.includes("Don't Save")&&buttons.includes('Cancel'),'Unsaved choices missing');return {choices:buttons,cancelRetainedEdit:true,pid:s.pid};});
await check('D-MEDIA-SEARCH',async()=>{let u=await ui();const field=u.widgets.find(w=>w.class==='MediaSearchField'),before=names(media(u));assert(before.includes('pattern_24.mov')&&before.includes('motion_25.mp4')&&before.includes('Secondary'),'Search fixture needs matching media and nonmatching controls');let observation;try{await n('text',{target:field.id,text:'pattern_24'});await n('key',{target:field.id,key:'Return'});observation=await until(async()=>{const a=await ui(),status=a.widgets.find(w=>w.name==='mediaSearchStatus')?.text;const results=media(a)?.model||[];return status==='Search unavailable'||a.widgets.find(w=>w.id===field.id)?.text==='pattern_24'&&!/searching|pending|loading/i.test(status||'')&&results.some(r=>r[0]==='pattern_24.mov')&&!results.some(r=>['motion_25.mp4','Secondary'].includes(r[0]))?a:null;});await writeJSON(path.join(s.root,'search-observed.json'),observation);}finally{await n('text',{target:field.id,text:''});await until(async()=>JSON.stringify(names(media(await ui())))===JSON.stringify(before));}const status=observation.widgets.find(w=>w.name==='mediaSearchStatus')?.text;if(status==='Search unavailable'){const e=Error('Live search reports Search unavailable in this isolated build; clearing the query restores all media. Search service/fixture setup is still required.');e.status='Blocked';throw e;}assert(media(observation).model.some(r=>r[0]==='pattern_24.mov')&&!names(media(observation)).some(v=>['motion_25.mp4','Secondary'].includes(v)),'Search did not filter matching media from nonmatching controls');return {query:'pattern_24',results:names(media(observation)),clearRestored:true};});
await check('D-EXPORT-CANCEL',async()=>{await focus();let u=await ui();await n('action',{target:u.actions.find(a=>a.name==='exportVideoAction').id});u=await until(async()=>{const a=await ui();return a.widgets.some(w=>w.name==='exportDialog')?a:null;});const dialog=u.widgets.find(w=>w.name==='exportDialog'),ws=u.widgets.filter(w=>w.window===dialog.id),output=path.join(s.root,'cancel-must-not-exist.mp4'),before=snapshotState(await timeline());await setExportOutput({n,ui},dialog.id,output);await n('click',{target:ws.find(w=>w.text==='Cancel'&&w.class==='QPushButton').id});await until(async()=>!(await ui()).widgets.some(w=>w.name==='exportDialog'));await pause(300);let exists=true;try{await stat(output);}catch(e){if(e.code!=='ENOENT')throw e;exists=false;}assert(!exists,'Cancelled export wrote output');same(snapshotState(await timeline()),before,'Export cancel project');return {outputAbsent:true,projectUnchanged:true};});
report.completed=true;await writeJSON(path.join(s.root,'desktop-paths-report.json'),report);console.log(JSON.stringify(report,null,2));if(report.results.some(r=>r.status!=='Pass'))process.exitCode=1;
