import path from 'node:path';
import {checks,curveResetControl,isNeutralCurve} from './check-support.mjs';
import {writeJSON} from '../runner/files.mjs';
import {assert,same,pause,clips} from '../runner/engine.mjs';
import {readPPM,pixelDifference} from '../runner/pixels.mjs';
const {s,n,c,ui,until,check:runCheck,activate,action,openTimeline,finish}=await checks(process.argv[2],'desktop-curves-report.json');
const check=(id,fn)=>runCheck(id,async()=>{try{return await fn();}finally{await writeJSON(path.join(s.root,id+'-ui.json'),await ui());}});
async function fixture(name){const t=await c('timeline.create',{name,video_format:{preset:'hd_1080p_24'},audio:{sample_rate:48000,channels:2}});await c('timeline.place_cuts',{id:name,timeline_id:t.timeline_id,cuts:[0,6].map((at,i)=>({id:'clip'+i,source:{asset_id:s.assets.plate},source_range:{start_seconds:1,end_seconds:5},streams:'video_only',destination:{at:{seconds:at,track:t.tracks.find(t=>t.kind==='video').track_id}}}))});const entries=clips(await c('timeline.inspect',{timeline_id:t.timeline_id})),v=await openTimeline(name);return {id:t.timeline_id,entries,v};}
async function frame(id,at,label){const p=path.join(s.root,label+'.ppm');await c('render.export_still',{timeline_id:id,time:{value:at*24,rate:24},output:p});return readPPM(p);}
const graph=(f,i)=>c('graph.get_clip_graph',{timeline_id:f.id,clip_id:f.entries[i].clip_id});
async function select(f,i){await activate(f.v);await n('key',{target:f.v.id,key:'V'});await n('click',{target:f.v.id,x:i?110:25,y:f.v.height-30});await c('playback.seek',{time:i?7:1});}
async function editor(panel){return until(async()=>{const u=await ui(),owner=u.widgets.find(w=>w.class.endsWith(panel));return owner&&u.widgets.find(w=>{if(!w.class.endsWith('CurveEditorWidget'))return false;let p=w;while(p){if(p.id===owner.id)return true;p=u.widgets.find(x=>x.id===p.parent);}return false;});});}
async function gesture(w){await activate(w);await n('drag',{target:w.id,x:Math.round(w.width*.5),y:Math.round(w.height*.5),toX:Math.round(w.width*.5),toY:Math.round(w.height*.25)});}
async function reset(f,index,editorId,key,kind){
 const before=await graph(f,index),node=before.nodes.find(n=>n.params?.[key]);assert(node,'Edited curve node is missing before reset');
 const control=curveResetControl(await ui(),editorId);await n('click',{target:control.id});
 const observed=path.join(s.root,kind+'-reset-graph.json');
 // Reset removes authored channel parameters; an absent parameter is the app's identity curve.
 const state=await until(async()=>{const g=await graph(f,index);await writeJSON(observed,g);const current=g.nodes.find(n=>n.node_id===node.node_id&&n.type===node.type);return current?.params&&(!Object.hasOwn(current.params,key)||isNeutralCurve(current.params[key],kind))?g:null;},{description:kind+' reset clears authored points or restores the neutral curve'});
 return {control:control.id,graph:observed,state};
}
await check('D-CURVE-RGB-CLIPBOARD',async()=>{
 const f=await fixture('RGB curve gesture smoke');await select(f,0);const baseline=await frame(f.id,1,'rgb-before');if(!(await ui()).widgets.some(w=>w.class.endsWith('CurvesPanel')))await action('Curves');if(!(await ui()).widgets.some(w=>w.tooltip==='Master'))await n('click',{target:(await ui()).widgets.find(w=>w.class.endsWith('CurveGroupChip')&&w.tooltip==='Expand this group').id});const master=await until(async()=>(await ui()).widgets.find(w=>w.tooltip==='Master'));await n('click',{target:master.id});const w=await editor('RgbCurvePanel');await gesture(w);const source=await until(async()=>{const g=await graph(f,0);return g.nodes.find(n=>n.params['grade.curve.master'])?.params['grade.curve.master'];});await writeJSON(path.join(s.root,'rgb-edited-graph.json'),await graph(f,0));const changed=await frame(f.id,1,'rgb-edited');assert(pixelDifference(baseline,changed)>1,'RGB gesture did not change pixels');await n('key',{target:w.id,key:'Ctrl+C'});await select(f,1);const destEditor=await editor('RgbCurvePanel');await activate(destEditor);await n('key',{target:destEditor.id,key:'Ctrl+V'});const copied=await until(async()=>{const g=await graph(f,1);return g.nodes.find(n=>n.params['grade.curve.master'])?.params['grade.curve.master'];});same(copied,source,'Pasted curve points');assert(pixelDifference(changed,await frame(f.id,7,'rgb-pasted'))<=1,'Pasted RGB curve pixels differ');const resetEvidence=await reset(f,1,destEditor.id,'grade.curve.master','rgb');assert(pixelDifference(baseline,await frame(f.id,7,'rgb-reset'))<=1,'Reset did not restore neutral pixels');same((await graph(f,0)).nodes.find(n=>n.params['grade.curve.master']).params['grade.curve.master'],source,'Reset copy preserves original');return {timeline:f.id,source,copied,independentReset:true,pixelsVerified:true,reset:resetEvidence};
});
await check('D-CURVE-HUE-RESET',async()=>{
 const f=await fixture('Hue curve gesture smoke');await select(f,0);const baseline=await frame(f.id,1,'hue-before');if(!(await ui()).widgets.some(w=>w.class.endsWith('CurvesPanel')))await action('Curves');if(!(await ui()).widgets.some(w=>w.tooltip==='Hue Shift'))await n('click',{target:(await ui()).widgets.find(w=>w.class.endsWith('CurveGroupChip')&&w.tooltip==='Expand this group').id});const hue=await until(async()=>(await ui()).widgets.find(w=>w.tooltip==='Hue Shift'));await n('click',{target:hue.id});const w=await editor('HueGroupCurvePanel');await gesture(w);const curve=await until(async()=>{const g=await graph(f,0);return g.nodes.find(n=>n.params['grade.hue_curve.hue_fx'])?.params['grade.hue_curve.hue_fx'];});await writeJSON(path.join(s.root,'hue-edited-graph.json'),await graph(f,0));assert(pixelDifference(baseline,await frame(f.id,1,'hue-edited'))>1,'Hue gesture did not change pixels');const resetEvidence=await reset(f,0,w.id,'grade.hue_curve.hue_fx','hue');assert(pixelDifference(baseline,await frame(f.id,1,'hue-reset'))<=1,'Hue reset did not restore neutral pixels');return {timeline:f.id,curve,pixelsChangedAndRestored:true,reset:resetEvidence};
});await openTimeline((await c('timeline.inspect',{timeline_id:s.main.id})).timeline.name);finish();
