import path from 'node:path';
import {checks,requireExactTimingFixture} from './check-support.mjs';
import {writeJSON} from '../runner/files.mjs';
import {assert,same,near,clips,snapshotState,pause} from '../runner/engine.mjs';
const {s,n,c,ui,until,check,activate,action,openTimeline,mediaItem,finish}=await checks(process.argv[2],'desktop-next-report.json');
const inspect=id=>c('timeline.inspect',{timeline_id:id}),key=(v,key)=>n('key',{target:v.id,key});let serial=0;
async function timeline(name,fps='24',streams='video_only',range=[1,5]){const t=await c('timeline.create',{name,video_format:{preset:'hd_1080p_'+fps},audio:{sample_rate:48000,channels:2}});const id=t.timeline_id;await c('timeline.place_cuts',{id:'next-place-'+ ++serial,timeline_id:id,cuts:[{id:'clip',source:{asset_id:s.assets.plate},source_range:{start_seconds:range[0],end_seconds:range[1]},streams,destination:{at:{seconds:0,track:t.tracks.find(t=>t.kind==='video').track_id}}}]});return id;}
async function undo(v,id,before){await key(v,'Ctrl+Z');return until(async()=>{const a=await inspect(id);return JSON.stringify(snapshotState(a))===JSON.stringify(snapshotState(before))?a:null;});}
async function select(v){await key(v,'V');await n('click',{target:v.id,x:400,y:v.height-30});await n('click',{target:v.id,x:10,y:v.height-30});}
await check('D-EDIT-SLIP',async()=>{const id=await timeline('Slip gesture smoke'),before=await inspect(id),v=await openTimeline(before.timeline.name);await writeJSON(path.join(s.root,'slip-baseline.json'),before);requireExactTimingFixture(before);await select(v);await key(v,'T');await until(async()=>(await ui()).widgets.some(w=>w.text==='Slip'&&w.checked));await n('drag',{target:v.id,x:25,y:v.height-30,toX:41,toY:v.height-30});const after=await until(async()=>{const a=await inspect(id);return clips(a)[0].source.source_range.start_seconds!==1?a:null;});await writeJSON(path.join(s.root,'slip-observed.json'),after);await writeJSON(path.join(s.root,'slip-undo.json'),await undo(v,id,before));await key(v,'V');const a=clips(after)[0],b=clips(before)[0];same(a.timeline_range,b.timeline_range,'Slip keeps placement');near(a.source.source_range.end_seconds-a.source.source_range.start_seconds,4,'Slip keeps source duration');assert(a.source.asset_id===b.source.asset_id&&a.source.projection_status==='exact',`Slip source authority invalid: ${JSON.stringify(a.source.projection_diagnostics)}`);return {before:b.source.source_range,after:a.source.source_range,placement:a.timeline_range,undo:true};});
await check('D-LINK-UNLINK-UI',async()=>{const id=await timeline('Link authoring smoke','24','linked'),before=await inspect(id),v=await openTimeline(before.timeline.name);await key(v,'V');await key(v,'Ctrl+A');await key(v,'Ctrl+Alt+L');const unlinked=await until(async()=>{const a=await inspect(id);return a.links.length===0?a:null;});await select(v);await key(v,'.');const independent=await until(async()=>{const a=await inspect(id);return clips(a).some(x=>x.timeline_range.start_seconds>0)?a:null;});await undo(v,id,unlinked);await key(v,'Ctrl+A');await key(v,'Ctrl+Alt+L');const linked=await until(async()=>{const a=await inspect(id);return a.links.length===1?a:null;});const toggle=(await ui()).widgets.find(w=>w.text==='Linked'&&w.name==='panelChromeAction');const original=toggle.checked;try{if(!original)await key(v,'Ctrl+Shift+L');await select(v);await key(v,'.');const together=await until(async()=>{const a=await inspect(id);return clips(a).every(x=>x.timeline_range.start_seconds>0)?a:null;});await undo(v,id,linked);const video=independent.tracks.find(x=>x.address==='V1').items.find(x=>x.kind==='clip'),audio=independent.tracks.find(x=>x.address==='A1').items.find(x=>x.kind==='clip');near(video.timeline_range.start_seconds,1/24,'Unlinked video');near(audio.timeline_range.start_seconds,0,'Unlinked audio');for(const x of clips(together))near(x.timeline_range.start_seconds,1/24,'Relinked streams');return {unlink:true,independentNudge:true,relink:true,linkedNudge:true};}finally{if(!original)await key(v,'Ctrl+Shift+L');}});
await check('D-BLADE-NO-SELECTION',async()=>{const id=await timeline('Unselected blade smoke','24','linked'),before=await inspect(id),v=await openTimeline(before.timeline.name);await writeJSON(path.join(s.root,'unselected-blade-baseline.json'),before);requireExactTimingFixture(before);await key(v,'V');await n('click',{target:v.id,x:400,y:v.height-30});await c('playback.seek',{time:2});await key(v,'B');const after=await until(async()=>{const a=await inspect(id);return clips(a).length===4?a:null;});await writeJSON(path.join(s.root,'unselected-blade-observed.json'),after);await writeJSON(path.join(s.root,'unselected-blade-undo.json'),await undo(v,id,before));for(const t of after.tracks){const parts=t.items.filter(x=>x.kind==='clip');same(parts.map(x=>x.timeline_range),[{start_seconds:0,end_seconds:2},{start_seconds:2,end_seconds:4}],'Unselected blade placement');same(parts.map(x=>x.source.source_range),[{start_seconds:1,end_seconds:3},{start_seconds:3,end_seconds:5}],'Unselected blade source');}assert(clips(after).every(x=>x.source.projection_status==='exact'),`Unselected blade timing authority rejected: ${JSON.stringify(clips(after).map(x=>x.source.projection_diagnostics))}`);return {splitStreams:2,undo:true};});
await check('D-FRACTIONAL-CLIPBOARD',async()=>{const src=await timeline('Fractional clipboard source','23_976','video_only',[0,1.001]),dst=await c('timeline.create',{name:'Fractional clipboard destination',video_format:{preset:'hd_1080p_29_97'},audio:{sample_rate:48000,channels:2}}),before=await inspect(src),empty=await inspect(dst.timeline_id),v=await openTimeline(before.timeline.name);await select(v);await n('clipboard-save');try{await key(v,'Ctrl+C');assert((await n('clipboard-mark')).formats.includes('application/x-wizard-timeline-clips'),'Clip clipboard missing');const target=await openTimeline(empty.timeline.name);await c('playback.seek',{time:.1001});await key(target,'Ctrl+V');const after=await until(async()=>{const a=await inspect(dst.timeline_id);return clips(a).length===1?a:null;});await writeJSON(path.join(s.root,'fractional-paste-observed.json'),after);await undo(target,dst.timeline_id,empty);const a=clips(after)[0];same(before.timeline.frame_rate,{numerator:24000,denominator:1001},'Source rate');same(after.timeline.frame_rate,{numerator:30000,denominator:1001},'Destination rate');assert(a.clip_id!==clips(before)[0].clip_id,'Paste reused identity');same(a.source,clips(before)[0].source,'Fractional clipboard preserves source');near(a.timeline_range.start_seconds,.1001,'Destination frame 3');near(a.timeline_range.end_seconds,1.1011,'Destination frame 33');same(snapshotState(await inspect(src)),snapshotState(before),'Source unchanged');return {rates:[before.timeline.frame_rate,after.timeline.frame_rate],range:a.timeline_range,undo:true};}finally{assert((await n('clipboard-restore')).restored,'Clipboard restoration failed');}});
await openTimeline((await inspect(s.main.id)).timeline.name);await c('project.checkpoint');await writeJSON(path.join(s.root,'next-ui.json'),await ui());finish();
