import path from 'node:path';
import {captureDesktop} from './diagnostics.mjs';
import {readFile,writeFile,unlink,mkdir,cp,open} from 'node:fs/promises';
import {getJob,sourceRun} from './hub.mjs';
import {prepareDesktop,launchDesktop,desktopCall,nativeCall,stopDesktop,verifyDesktopPaths,verifyDesktopOwner} from './adapter.mjs';
import {ROOT,dataDirectory,readJSON,writeJSON,fingerprint,sha} from '../runner/files.mjs';
import {assert,pause,command} from '../runner/engine.mjs';
const data=dataDirectory(),id=process.argv[2];let job=getJob(data,id),live,sessionFile,stop=false;
process.on('SIGTERM',()=>{stop=true;});process.on('SIGINT',()=>{stop=true;});
const update=async(fields)=>{job={...job,...fields,updatedAt:new Date().toISOString()};await writeJSON(path.join(job.root,'job.json'),job);};
async function capture(label){
 const timeline=await captureDesktop(sessionFile,path.join(job.root,'captures',label));
 await update({lastCapture:label,captures:[...(job.captures||[]),label]});return timeline;
}

try{
 const origin=sourceRun(data,job.sourceRun),s=origin.session;verifyDesktopPaths(s);assert(origin.reportHash===job.sourceReportHash,'Original report changed');
 assert((await fingerprint(s.app,{packageTree:true})).sha256===s.guiHash,'Frozen source GUI changed');assert(await sha(s.desktopCli)===s.desktopCliHash,'Frozen paired CLI changed');assert(s.qtCocoa&&await sha(s.qtCocoa.loadedPath)===s.qtCocoa.sha256,'Frozen smoke Qt plugin changed');
 if(job.kind==='course'||job.kind==='service'){
  await update({state:'Running'});const receipt=await command(process.execPath,[path.join(ROOT,job.kind==='service'?'desktop/service-run.mjs':'desktop/run.mjs'),s.app,s.qtCocoa.loadedPath,s.desktopCli],{timeout:15*60*1000});await writeJSON(path.join(job.root,'execution.json'),receipt);
  const objects=receipt.stdout.split('\n').flatMap(line=>{try{return [JSON.parse(line)];}catch{return [];}}),start=objects.find(x=>x.session);
  assert(start,'Course did not publish a session; inspect execution.json');const output=await readJSON(path.join(path.dirname(start.session),'desktop-course-report.json'));
  await update({state:output.status==='Pass'?'Passed':'Failed',runId:path.basename(path.dirname(start.session)),message:`Course completed: ${output.results.filter(r=>r.status==='Pass').length}/${output.results.length} passed.`});
 }else{
  const prepared=await prepareDesktop(s.app,s.qtCocoa.loadedPath,s.desktopCli);assert(prepared.guiHash===s.guiHash&&prepared.desktopCliHash===s.desktopCliHash&&prepared.fixtureHash===s.fixtureHash,'Reproduction identities differ from the failed run');
  sessionFile=path.join(prepared.root,'session.json');await update({sessionFile,reproductionRun:path.basename(prepared.root)});assert(!stop,'Setup cancelled');live=await launchDesktop(prepared);
  const current=await readJSON(sessionFile);await desktopCall(sessionFile,'render.bind_timeline',{timeline_id:current.main.id,playhead_frame:48});let ui=await nativeCall(sessionFile,'inspect');const main=ui.widgets.find(w=>w.class==='MainWindow');await nativeCall(sessionFile,'activate',{target:main.id});
  if(['D-EDIT-SPLIT-REDO','D-EDIT-TRIM'].includes(job.caseId)){const v=ui.widgets.filter(w=>w.class==='TimelineWidget').sort((a,b)=>a.y-b.y)[0];await nativeCall(sessionFile,'click',{target:v.id,x:25,y:115});await desktopCall(sessionFile,'playback.seek',{time:2});}
  const baseline=await capture('before'),definition=job.definition,original=origin.report.results.find(r=>r.id===job.caseId);
  const parcel={format:'wizard-human-handoff/v1',case:definition,source:{runId:job.sourceRun,reportHash:job.sourceReportHash,result:original,guiHash:s.guiHash,cliHash:s.desktopCliHash,qtHash:s.qtCocoa.sha256},setup:{method:'Fresh GP from the failed run’s frozen GUI, paired CLI and Qt plugin; not a replay of the suspect action',sessionFile,bundle:current.bundle,pid:current.pid,url:current.url,timelineId:current.main.id,clipId:current.clip,revision:baseline.bundle_revision,expiresAt:new Date(Date.now()+30*60*1000).toISOString()},diagnostics:{profile:job.diagnosticProfile,captured:['timeline state','visible Qt controls','window image (Metal pixels may be absent)','last 32 KB of each app log'],notCaptured:['CPU/GPU profile','system-wide tracing','provider traffic']}};
  await writeJSON(path.join(job.root,'parcel.json'),parcel);
  await writeFile(path.join(job.root,'brief.md'),`# ${definition.title}\n\nAutomated result: ${original.status}. ${original.error||''}\n\n## Prepared setup\n\nA separate synthetic Golden Project is open in the frozen smoke build. The suspect action has not been executed. This setup expires after 30 minutes; Finish saves and stops it sooner. Original evidence stays unchanged.\n\n## Expected\n\n${definition.expected}\n\n## Your check\n\n${definition.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}\n\n## Record the finding\n\nChoose Confirmed defect, Could not reproduce, Setup blocked, or Needs investigation. Include what you saw, the step, and whether diagnostic state agrees. Your observation is separate from the automated verdict.\n`);
  const q=x=>"'"+String(x).replaceAll("'","'\\''")+"'";
  const inspect=`${q(current.desktopCli)} --url ${q(current.url)} --no-spawn --bundle ${q(current.bundle)} timeline inspect --json --params ${q(JSON.stringify({timeline_id:current.main.id}))}`;
  await writeFile(path.join(job.root,'oz-prompt.txt'),`Help me investigate ${job.caseId}: ${definition.title}.\nThis is an investigation, not a request to fix application code or to make the test pass.\nFailed run: ${job.sourceRun}; automated observation: ${original.error||original.status}\nExpected: ${definition.expected}\nUse ONLY this prepared project: ${current.bundle}\nOwned app PID: ${current.pid}; endpoint: ${current.url}; timeline: ${current.main.id}; clip: ${current.clip}.\nPrepared revision: ${baseline.bundle_revision}. Expiry: ${parcel.setup.expiresAt}. Verify the process and project binding, then read the current revision; stop if they differ from this session or the session has ended. Do not fall back to another running app.\nRead-only timeline command (paired CLI):\n${inspect}\n\nGuide me through these steps one at a time:\n${definition.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}\n\nLet ME perform the action under test. Do not replace the failed UI action with a CLI operation, repair metadata, retry uncertain mutations, or claim that a visual success clears a state inconsistency. Ask me to capture diagnostics after the action and help compare with the before capture. Do not generate media, spend money, change personal configuration, upload logs, or publish a bug. Finish with a concise expected/actual/reproduction/evidence summary for my review. If Oz cannot access this endpoint, use the dashboard's Capture diagnostics and manual brief; do not change Oz configuration automatically.\n`);
  await writeFile(path.join(job.root,'runbook.json'),JSON.stringify({preparation:'desktop/worker.mjs handoff branch',inputs:parcel.setup,readOnlyCommands:[inspect],testedGestureOwnedBy:'human',capture:'Dashboard Capture diagnostics',finish:'Dashboard Finish setup'},null,2));
  await writeFile(path.join(job.root,'bug-draft.md'),`# Draft: ${definition.title}\n\nStatus: awaiting human investigation; not published.\n\n## Build and origin\n\nInstrumented local smoke build, not release acceptance.\nGUI SHA-256: ${s.guiHash}\nPaired CLI SHA-256: ${s.desktopCliHash}\nQt plugin SHA-256: ${s.qtCocoa.sha256}\nSource run: ${job.sourceRun}\nSource report SHA-256: ${job.sourceReportHash}\n\n## Expected\n\n${definition.expected}\n\n## Automated observation\n\n${original.error||original.status}\n\n## Reproduction\n\n${definition.steps.map((v,i)=>`${i+1}. ${v}`).join('\n')}\n\n## Local evidence\n\nParcel, read-only CLI runbook, before/after state, widget observations, window capture and bounded logs are stored in this handoff folder. Original run evidence is retained separately. Logs may contain identifying context; review before any external sharing. Heavy profiling is not enabled in this first version.\n\n## Human findings\n\n`);
  await update({state:'Ready',expiresAt:parcel.setup.expiresAt,message:'Prepared for a human. The suspect action has not been executed.'});
  while(!stop&&Date.now()<Date.parse(parcel.setup.expiresAt)&&live.child.exitCode===null&&!live.child.signalCode){
   const request=path.join(job.root,'request.json');let r;try{r=await readJSON(request);}catch(e){if(e.code!=='ENOENT')throw e;}
   if(r){await unlink(request);if(r.action==='finish')break;if(r.action==='profile'){const s=await readJSON(sessionFile);verifyDesktopOwner(s);const label='cpu-'+Date.now(),dir=path.join(job.root,'captures',label);await mkdir(dir,{recursive:true});const receipt=await command('/usr/bin/sample',[String(s.pid),'5','-file',path.join(dir,'sample.txt')],{timeout:15000});await writeJSON(path.join(dir,'receipt.json'),receipt);await update({lastCapture:label,captures:[...(job.captures||[]),label],message:receipt.code===0?'Captured a five-second CPU sample of the owned app.':'CPU sample failed; its receipt is retained.'});}if(r.action==='capture'){await capture('after-'+Date.now());await update({message:'Captured current state, window and bounded application logs.'});}}
   await pause(250);
  }
  if(live.child.exitCode===null&&!live.child.signalCode){await capture('final');await stopDesktop(sessionFile);await live.closed;}
  await update({state:'Finished',message:'Setup ended. Project and diagnostics are retained; human findings remain separate.'});
 }
}catch(e){await update({state:'Failed',message:e.message});process.exitCode=1;}
finally{if(live&&live.child.exitCode===null&&!live.child.signalCode)try{await stopDesktop(sessionFile);await live.closed;}catch(e){await update({cleanupError:e.message,message:'Cleanup needs attention. Inspect the owned app before starting another setup.'});}}
