import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {promisify} from 'node:util';
import {execFile} from 'node:child_process';
import {mkdir,mkdtemp,readFile,readdir,realpath,rename,rm,stat,access} from 'node:fs/promises';
import {constants,createWriteStream} from 'node:fs';
import {pipeline} from 'node:stream/promises';
import {Transform} from 'node:stream';
import {sha,writeJSON,digest} from './runner/files.mjs';
const exec=promisify(execFile),repository='story-wizard/wizard-release',limit=5*1024**3;
const gh=async endpoint=>JSON.parse((await exec('gh',['api',endpoint],{timeout:30000,maxBuffer:12*1024**2})).stdout);
export const buildChannel=tag=>/^nightly[-/]/i.test(tag)?'Nightly':/^(v?\d+\.\d+\.\d+($|[-+])|v?story-weekly-|release[-/])/i.test(tag)?'Release':'Tagged';
export function releaseBuilds(releases,runs=[]){
 const workflows=new Map(runs.map(r=>[String(r.id),r]));
 return releases.filter(r=>!r.draft&&r.published_at).flatMap(r=>{
  const runId=r.body?.match(/<!--\s*wizard-build:\s*[a-f0-9]+\s+run:(\d+)\s*-->/i)?.[1]||r.tag_name.match(/-r(\d+)$/)?.[1]||null,run=workflows.get(runId);
  const requestedBy=run?.triggering_actor?.login||run?.actor?.login||null;
  return (r.assets||[]).filter(a=>/mac(os)?[^/]*\.zip$/i.test(a.name)).map(a=>({tag:r.tag_name,label:r.name||r.tag_name,publishedAt:r.published_at,channel:buildChannel(r.tag_name),requestedBy,buildRunId:runId,buildEvent:run?.event||null,buildRunUrl:run?.html_url||null,publisher:r.author?.login||null,assetId:a.id,asset:a.name,bytes:a.size,expectedDigest:a.digest||null,url:a.browser_download_url,architecture:/arm64|aarch64/i.test(a.name)?'Apple Silicon':/x64|x86_64|intel/i.test(a.name)?'Intel':/universal/i.test(a.name)?'Universal':'Unspecified'}));
 }).sort((a,b)=>['Release','Nightly','Tagged'].indexOf(a.channel)-['Release','Nightly','Tagged'].indexOf(b.channel)||b.publishedAt.localeCompare(a.publishedAt));
}
export async function localBuilds(dataDir){const root=path.join(dataDir,'builds'),builds=[];let names;try{names=await readdir(root);}catch(e){if(e.code==='ENOENT')return [];throw e;}for(const name of names.filter(n=>!n.startsWith('.'))){try{const b=JSON.parse(await readFile(path.join(root,name,'build.json'),'utf8'));await access(b.app);builds.push({...b,available:true});}catch{}}return builds;}
async function recentPages(endpoint,key){const rows=[];for(let page=1;page<=3;page++){const response=await gh(`${endpoint}?per_page=100&page=${page}`),items=key?response[key]:response;rows.push(...items);if(items.length<100)break;}return rows;}
export async function findBuilds(dataDir){
 const [releases,runs,user]=await Promise.allSettled([recentPages(`repos/${repository}/releases`),recentPages(`repos/${repository}/actions/workflows/build-release.yml/runs`,'workflow_runs'),gh('user')]);
 if(releases.status==='rejected')throw releases.reason;
 const local=await localBuilds(dataDir);
 return {repository,limit:300,fetchedAt:new Date().toISOString(),currentUser:user.status==='fulfilled'?user.value.login:null,userLookupError:runs.status==='rejected'||user.status==='rejected'?'Build user lookup unavailable. Refresh to try again.':null,builds:releaseBuilds(releases.value,runs.status==='fulfilled'?runs.value:[]).map(b=>({...b,app:local.find(l=>l.assetId===b.assetId)?.app||null}))};
}
export async function validateApp(input){if(typeof input!=='string'||!path.isAbsolute(input)||!input.endsWith('.app'))throw Error('Choose an absolute path to a Wizard .app.');const app=await realpath(input);if(!(await stat(app)).isDirectory())throw Error('App bundle is not a directory.');const plist=path.join(app,'Contents/Info.plist');const {stdout}=await exec('/usr/bin/plutil',['-extract','CFBundleExecutable','raw','-o','-',plist],{timeout:5000});const binary=stdout.trim();if(!/^wizard(-bin)?$/i.test(binary))throw Error('This bundle does not identify a Wizard executable.');await access(path.join(app,'Contents/MacOS',binary),constants.X_OK);return app;}
async function appIn(root){const apps=[];async function walk(dir,depth=0){if(depth>5)return;for(const item of await readdir(dir,{withFileTypes:true})){if(!item.isDirectory()||item.name==='__MACOSX')continue;const full=path.join(dir,item.name);if(item.name.endsWith('.app'))apps.push(full);else await walk(full,depth+1);}}await walk(root);if(apps.length!==1)throw Error('The ZIP must contain exactly one Wizard app.');return validateApp(apps[0]);}
export async function receiveArchive(input,file){let bytes=0;await pipeline(input,new Transform({transform(chunk,encoding,next){bytes+=chunk.length;next(bytes>limit?Error('ZIP exceeds the 5 GB limit.'):null,chunk);}}),createWriteStream(file,{flags:'wx'}));}
export async function buildStage(dataDir){const root=path.join(dataDir,'builds');await mkdir(root,{recursive:true});return realpath(await mkdtemp(path.join(root,'.import-')));}
export async function importBuild(dataDir,input,{stage:provided}={}){
 const count=['path','url','tag','assetId'].filter(k=>input[k]!==undefined).length;if(count!==1)throw Error('Choose one local path, HTTPS URL, tag or GitHub asset.');
 if(input.path?.endsWith('.app')){const app=await validateApp(input.path);const build={app,label:path.basename(app),available:true,source:'local'},folder=path.join(dataDir,'builds','local-'+digest(app));await mkdir(folder,{recursive:true});await writeJSON(path.join(folder,'build.json'),build);return build;}
 const stage=provided||await buildStage(dataDir),archive=path.join(stage,'package.zip');let source={};
 try{
  if(input.path){if(!path.isAbsolute(input.path)||!input.path.toLowerCase().endsWith('.zip'))throw Error('Choose an absolute ZIP or app path.');if(!provided)await receiveArchive((await import('node:fs')).createReadStream(await realpath(input.path)),archive);source={source:'zip',label:path.basename(input.path)};}
  else if(input.url){let url;try{url=new URL(input.url);}catch{throw Error('Enter a valid HTTPS ZIP URL.');}if(url.protocol!=='https:'||url.username||url.password)throw Error('Use an HTTPS URL without credentials.');const github=url.hostname==='github.com'&&url.pathname.match(/^\/story-wizard\/wizard-release\/releases\/download\/(.+)\/([^/]+)$/);if(github){const release=await gh(`repos/${repository}/releases/tags/${encodeURIComponent(decodeURIComponent(github[1]))}`),asset=release.assets.find(a=>a.name===decodeURIComponent(github[2]));if(!asset)throw Error('GitHub asset not found.');input={assetId:asset.id};}else{try{await exec('/usr/bin/curl',['--fail','--location','--proto','=https','--proto-redir','=https','--max-time','600','--max-filesize',String(limit),'--output',archive,'--',url.href],{timeout:610000,maxBuffer:1024**2});}catch{throw Error('HTTPS download failed. Check the ZIP URL and access.');}source={source:'url',label:path.basename(url.pathname)||'Downloaded Wizard',url:url.origin+url.pathname};}}
  if(input.tag||input.assetId){let asset;if(input.tag){if(typeof input.tag!=='string'||!input.tag||input.tag.length>200)throw Error('Enter a valid release tag.');const r=await gh(`repos/${repository}/releases/tags/${encodeURIComponent(input.tag)}`);const builds=releaseBuilds([r]);if(builds.length!==1)throw Error('This tag must have one macOS ZIP. Choose its asset in the finder.');asset=builds[0];}else{if(!Number.isSafeInteger(input.assetId)||input.assetId<=0)throw Error('Invalid GitHub asset.');const a=await gh(`repos/${repository}/releases/assets/${input.assetId}`);if(!/mac(os)?[^/]*\.zip$/i.test(a.name))throw Error('Choose a macOS ZIP asset.');asset={assetId:a.id,asset:a.name,bytes:a.size,expectedDigest:a.digest||null,url:a.browser_download_url,label:a.name};}if(/[?*\[\]]/.test(asset.asset))throw Error('Unsupported wildcard in asset name.');if(asset.bytes>limit)throw Error('ZIP exceeds the 5 GB limit.');const destination=path.join(dataDir,'builds','gh-'+asset.assetId);try{const cached=JSON.parse(await readFile(path.join(destination,'build.json'),'utf8'));await validateApp(cached.app);if(cached.assetId!==asset.assetId||asset.expectedDigest?.startsWith('sha256:')&&asset.expectedDigest!=='sha256:'+cached.archiveHash)throw Error('Cached build archive identity differs from GitHub.');return {...cached,available:true};}catch(e){if(e.code!=='ENOENT')throw Error('Cached build needs inspection: '+e.message);}await exec('gh',['release','download','--repo',repository,'--pattern',asset.asset,'--output',archive,'--',asset.tag||decodeURIComponent(new URL(asset.url).pathname.match(/\/releases\/download\/(.+)\/[^/]+$/)[1])],{timeout:610000,maxBuffer:1024**2});source={...asset,source:'github'};}
  await exec('python3',[path.join(path.dirname(fileURLToPath(import.meta.url)),'scripts/validate-build-zip.py'),archive],{timeout:60000,maxBuffer:1024**2});
  await mkdir(path.join(stage,'unpacked'));await exec('/usr/bin/ditto',['-x','-k',archive,path.join(stage,'unpacked')],{timeout:300000,maxBuffer:1024**2});
  const app=await appIn(path.join(stage,'unpacked')),hash=await sha(archive);if(source.bytes&&(await stat(archive)).size!==source.bytes)throw Error('Downloaded archive size differs from GitHub.');if(source.expectedDigest?.startsWith('sha256:')&&source.expectedDigest!=='sha256:'+hash)throw Error('Downloaded archive differs from GitHub digest.');const destination=path.join(dataDir,'builds',source.assetId?'gh-'+source.assetId:hash);const result={...source,app:path.join(destination,path.relative(stage,app)),archiveHash:hash,available:true,downloadedAt:new Date().toISOString()};
  try{const cached=JSON.parse(await readFile(path.join(destination,'build.json'),'utf8'));await validateApp(cached.app);return cached;}catch(e){if(e.code!=='ENOENT')throw e;}
  await rm(archive);await writeJSON(path.join(stage,'build.json'),result);await rename(stage,destination);return result;
 }finally{await rm(stage,{recursive:true,force:true});}
}
