import path from 'node:path';
import {mkdir,copyFile,realpath} from 'node:fs/promises';
import {assert,near,same,snapshotState,clips,clip,bounds,OutcomeError} from './engine.mjs';
import {remainingCases} from './remaining-checks.mjs';
import {runtimeCases} from './runtime-checks.mjs';
import {extendedCases} from './extended-checks.mjs';
import {renderCases} from './render-checks.mjs';
import {inside} from './files.mjs';

export {ProjectSession as CaseContext} from './interactions.mjs';
export const cases={
  ...renderCases,
  ...extendedCases,
  ...remainingCases,
  ...runtimeCases,
  async 'A-CLI-01'(c){await c.create();const p=await c.call('project.get_name');assert(p.name===`Golden ${c.id}`,'Wrong project name.');assert(c.engine.revisions.get(c.bundle)?.length>0,'Project revision is absent.');return 'Owned packaged endpoint created and read the expected project.';},
  async 'IN-01'(c){
    await c.create();await c.call('media.add_media_root',{path:c.mediaRoot});const ids=new Set();
    for(const f of c.fixtures.files){const id=await c.import(f.id);assert(!ids.has(id),'Distinct fixture files unexpectedly share an asset identity.');ids.add(id);const resolved=await c.call('media.resolve_path',{asset_id:id});same(await realpath(resolved.path),await realpath(path.join(c.mediaRoot,f.file)),'Resolved fixture path');const actual=await c.call('media.probe',{path:resolved.path});for(const [key,value] of Object.entries(f.expected)){if(typeof value==='boolean')assert(actual[key]===value,`${f.file}: wrong ${key}`);else if(key==='duration')assert(Number.isFinite(actual.duration)&&Math.abs(actual.duration-value)<.051,`${f.file}: wrong duration`);else near(actual[key],value,`${f.file} ${key}`);}}
    await c.ingest();return 'Eight fixtures registered, resolved and probed. Both editorial video fixtures completed local ingest with matching durable source records. Model analysis was disabled.';
  },
  async 'IN-03'(c){await c.create();const folder=path.join(c.engine.root,'external',c.id);await mkdir(folder,{recursive:true});const file=path.join(folder,'outside.mov');await copyFile(path.join(c.mediaRoot,'pattern_24.mov'),file);assert(!inside(path.dirname(c.bundle),file),'Fixture is not outside the bundle parent.');const id=await c.import('plate',file);await c.call('project.checkpoint');await c.call('project.close');await c.call('project.open');const resolved=await c.call('media.resolve_path',{asset_id:id});same(await realpath(resolved.path),await realpath(file),'Reopened external source');const probe=await c.call('media.probe',{path:resolved.path});near(probe.width,1920,'External source width');near(probe.fps,24,'External source FPS');return 'External source identity and path survived project close/reopen.';},
  async 'A-TL-01'(c){
    await c.setup();const inserted=await c.move(c.main,[c.a],c.main,6,{copy:true,ripple:{destination:true}});const insertedId=inserted.result.clips.find(i=>i.source_clip_id===c.a)?.clip_id||inserted.result.clips[0]?.clip_id;assert(insertedId&&insertedId!==c.a,'Copy did not create an independent clip.');let s=await c.inspect(c.main);assert(clips(s).length===3,'Insert produced the wrong clip count.');bounds(clip(s,c.a),0,4,1,5);bounds(clip(s,insertedId),6,10,1,5);bounds(clip(s,c.b),10,12,0,2);
    await c.move(c.main,[c.b],c.main,7,{copy:true,collision:'overwrite'});s=await c.inspect(c.main);
    const observed=clips(s).map(i=>[i.source.asset_id,i.timeline_range.start_seconds,i.timeline_range.end_seconds,i.source.source_range.start_seconds,i.source.source_range.end_seconds]).sort((a,b)=>a[1]-b[1]);
    same(observed,[[c.assets.plate,0,4,1,5],[c.assets.plate,6,7,1,2],[c.assets.motion,7,9,0,2],[c.assets.plate,9,10,4,5],[c.assets.motion,10,12,0,2]],'Overwrite layout');bounds(clip(s,c.a),0,4,1,5);bounds(clip(s,c.b),10,12,0,2);return 'Insert ripple and occupied-range overwrite matched exact clip and source intervals.';
  },
  async 'A-TL-02'(c){
    await c.setup();await c.call('timeline.split_clips',{id:'split-single',timeline_id:c.main.id,splits:[{id:'a',clips:[{clip_id:c.a}],points:{timeline_seconds:[2]}}],streams:'video_only'});let s=await c.inspect(c.main);const parts=clips(s).filter(i=>i.source.asset_id===c.assets.plate).sort((a,b)=>a.timeline_range.start_seconds-b.timeline_range.start_seconds);assert(parts.length===2,'Single split should yield two segments.');bounds(parts[0],0,2,1,3);bounds(parts[1],2,4,3,5);bounds(clip(s,c.b),6,8,0,2);
    await c.call('timeline.manage_tracks',{id:'add-v2',timeline_id:c.main.id,edits:[{id:'v2',action:'add',kind:'video',name:'V2'}]});s=await c.inspect(c.main);const v2=s.tracks.find(t=>t.address==='V2');assert(v2,'V2 was not created.');const top=(await c.place(c.main,c.assets.plate,0,1,5,{track:v2.track_id}))[0].clip_id;
    await c.call('timeline.split_clips',{id:'split-multiple',timeline_id:c.main.id,splits:[{id:'lower-track',clips:[{clip_id:parts[0].clip_id}],points:{timeline_seconds:[1]}},{id:'upper-track',clips:[{clip_id:top}],points:{timeline_seconds:[1]}}],streams:'video_only'});s=await c.inspect(c.main);
    const ranges=clips(s).filter(i=>i.source.asset_id===c.assets.plate).map(i=>[i.track_id,i.timeline_range.start_seconds,i.timeline_range.end_seconds,i.source.source_range.start_seconds,i.source.source_range.end_seconds]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));
    const expected=[[c.main.video,0,1,1,2],[c.main.video,1,2,2,3],[c.main.video,2,4,3,5],[v2.track_id,0,1,1,2],[v2.track_id,1,4,2,5]].sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));same(ranges,expected,'Multiple split ranges');bounds(clip(s,c.b),6,8,0,2);return 'Single and multiple explicit clip splits preserve contiguous source windows.';
  },
  async 'A-TL-03'(c){await c.setup();await c.call('timeline.trim_extend_edges',{id:'trim',timeline_id:c.main.id,edits:[{id:'shorten-a',clip:{clip_id:c.a},change:{adjust_edges:{out:{trim_seconds:1}}}}],ripple:false,streams:'video_only'});bounds(clip(await c.inspect(c.main),c.a),0,3,1,4);await c.call('timeline.slip_clips',{id:'slip',timeline_id:c.main.id,slips:[{id:'later-source',clips:[{clip_id:c.a}],change:{later_source_seconds:1}}],streams:'video_only'});bounds(clip(await c.inspect(c.main),c.a),0,3,2,5);await c.call('timeline.remove_clips',{id:'ripple-remove',timeline_id:c.main.id,clips:[{clip_id:c.a}],ripple:true,streams:'video_only'});const s=await c.inspect(c.main);assert(clips(s).length===1,'Ripple removal left unexpected clips.');bounds(clip(s,c.b),3,5,0,2);return 'Trim, slip and ripple clip removal produced the exact expected intervals.';},
  async 'A-TL-04'(c){await c.setup();await c.move(c.main,[c.a],c.alternate,3,{copy:true});let destination=await c.inspect(c.alternate),source=await c.inspect(c.main);const copied=clips(destination).find(i=>i.source.asset_id===c.assets.plate);assert(copied&&copied.clip_id!==c.a,'Cross-rate copy did not mint an independent identity.');bounds(copied,3,7,1,5);near(copied.timeline_range.start_seconds*25,75,'Destination start frame');near(copied.timeline_range.end_seconds*25,175,'Destination end frame');bounds(clip(source,c.a),0,4,1,5);
    await c.move(c.main,[c.b],c.alternate,8);destination=await c.inspect(c.alternate);source=await c.inspect(c.main);assert(!clips(source).some(i=>i.clip_id===c.b),'Move retained the source clip.');const moved=clips(destination).find(i=>i.timeline_range.start_seconds===8);assert(moved?.source.asset_id===c.assets.motion,'Moved clip source changed.');bounds(moved,8,10,0,2);assert(clips(source).length===1&&clips(destination).length===3,'Cross-timeline copy/move count mismatch.');return '24-to-25 fps copy and move preserve source ranges and whole-second timing.';},
  async 'A-TL-05'(c){await c.setup();const t=await c.timeline('Linked AV',24),placed=await c.place(t,c.assets.plate,0,1,3,{streams:'linked'});const v=placed.find(p=>p.stream==='video')?.clip_id,a=placed.find(p=>p.stream==='audio')?.clip_id;assert(v&&a,'Linked placement omitted a stream.');let s=await c.inspect(t);assert(s.links.some(l=>l.members.some(m=>m.clip_id===v)&&l.members.some(m=>m.clip_id===a)),'Placed AV is not linked.');await c.move(t,[v],t,3,{expand_links:true,ripple:{source:false,destination:false}});s=await c.inspect(t);bounds(clip(s,v),3,5,1,3);bounds(clip(s,a),3,5,1,3);await c.call('timeline.set_clip_links',{id:'unlink',timeline_id:t.id,mode:'unlink',clips:[{clip_id:v},{clip_id:a}]});await c.move(t,[v],t,6,{expand_links:false,ripple:{source:false,destination:false}});s=await c.inspect(t);bounds(clip(s,v),6,8,1,3);bounds(clip(s,a),3,5,1,3);assert(!s.links.some(l=>l.members.some(m=>m.clip_id===v)||l.members.some(m=>m.clip_id===a)),'Unlink retained the pair.');return 'Linked audio follows a move; unlink makes subsequent video edits independent.';},
  async 'A-TL-06'(c){await c.setup();await c.call('timeline.manage_tracks',{id:'lock',timeline_id:c.main.id,edits:[{id:'lock-v1',action:'set_locked',tracks:[c.main.video],locked:true}]});const baseline=snapshotState(await c.inspect(c.main));assert(baseline.tracks.find(t=>t.track_id===c.main.video).locked,'Track did not lock.');await c.call('timeline.split_clips',{id:'refused-split',timeline_id:c.main.id,splits:[{id:'a',clips:[{clip_id:c.a}],points:{timeline_seconds:[2]}}]},['locked_or_protected','locked']);same(snapshotState(await c.inspect(c.main)),baseline,'State after rejected split');await c.call('timeline.move_clips',{id:'refused-move',source:{timeline_id:c.main.id,selection:{clip_ids:[c.a]}},destination:{timeline_id:c.main.id,at:{seconds:1,track:c.main.video}}},['locked_or_protected','locked']);same(snapshotState(await c.inspect(c.main)),baseline,'State after rejected move');return 'Both locked-track mutations were specifically rejected without changing state.';},
  async 'UP-01'(c){await c.setup();const history=[await c.both()];for(let i=0;i<20;i++){const t=i%2?c.alternate:c.main,id=i%2?c.c:c.a,pos=Math.floor(i/2)%2?0:1;await c.move(t,[id],t,pos);const after=await c.both();bounds(clip(after[i%2],id),pos,pos+(i%2?2:4),i%2?2:1,i%2?4:5);history.push(after);}for(let i=19;i>=0;i--){assert((await c.call('undo.undo')).moved===true,`Undo ${20-i} was a no-op.`);same(await c.both(),history[i],`Undo ${20-i}`);}for(let i=1;i<=20;i++){assert((await c.call('undo.redo')).moved===true,`Redo ${i} was a no-op.`);same(await c.both(),history[i],`Redo ${i}`);}return 'All 20 edits, 20 undos and 20 redos matched both timeline states.';},
  async 'A-LP-04'(c){await c.setup();const saved=await c.both(),checkpoint=await c.call('project.checkpoint'),revision=c.engine.revisions.get(c.bundle);assert(checkpoint.main_tip===revision,'Checkpoint did not bless the observed revision.');await c.move(c.main,[c.a],c.main,1);bounds(clip(await c.inspect(c.main),c.a),1,5,1,5);await c.call('project.discard_changes');same(c.engine.revisions.get(c.bundle),revision,'Discard revision');same(await c.both(),saved,'Discarded project');return 'Checkpoint and discard restored the exact saved revision and timelines.';},
  async 'A-LP-02'(c){await c.setup();await c.move(c.main,[c.a],c.main,1);const saved=await c.both(),settings=await c.call('project.get_settings');await c.call('project.checkpoint');const pid=c.engine.child.pid;await c.engine.stop();await c.engine.start();assert(c.engine.child.pid!==pid,'Restart did not create a new process.');await c.call('project.open');assert((await c.call('project.get_name')).name===`Golden ${c.id}`,'Reopened the wrong project.');same(await c.call('project.get_settings'),settings,'Reopened settings');same(await c.both(),saved,'Reopened timelines');for(const [key,id] of Object.entries(c.assets)){const f=c.fixtures.files.find(f=>f.id===key);same(await realpath((await c.call('media.resolve_path',{asset_id:id})).path),await realpath(path.join(c.mediaRoot,f.file)),'Reopened asset path');}return 'A new packaged headless process reopened identical project, settings, assets and edited timelines.';}
};
