import path from 'node:path';
import {readFile,writeFile,realpath,lstat} from 'node:fs/promises';
import {assert,same,near,clips,clip,bounds,snapshotState} from './engine.mjs';
import {inside,writeJSON} from './files.mjs';
import {ingestAssets,search,reopen,mixReport,still,evidence,insertEffect} from './interactions.mjs';
import {pixelStats,pixelDifference,visibleImage} from './pixels.mjs';

async function media(c){await c.create();await c.call('media.add_media_root',{path:c.mediaRoot});await c.import('plate');await c.import('motion');}
async function speech(c,{video=false}={}){
  await c.create();await c.call('media.add_media_root',{path:c.mediaRoot});const fixture=video?'speechVideo':'speech';await c.import(fixture);c.assets.speech=c.assets[fixture];
  await ingestAssets(c.engine,c.bundle,[{asset_id:c.assets.speech,media_path:path.join(c.mediaRoot,video?'comet_report.mov':'comet_report.wav')}],{speech:true});
  const sidecar=JSON.parse(await readFile(path.join(c.bundle,'assets/clips',c.assets.speech+'.json'),'utf8'));
  await writeJSON(path.join(path.dirname(c.bundle),'transcript.json'),sidecar);
  const t=sidecar.transcription;assert(t?.engine?.startsWith('coreml_parakeet_tdt_v2'),'Wrong speech engine.');
  for(const anchor of c.fixtures.speech.anchors)assert(t.full_text.toLowerCase().includes(anchor),`Transcript is missing ${anchor}.`);
  const words=t.sentences.flatMap(s=>s.words),duration=c.fixtures.files.find(f=>f.id==='speech').expected.duration;
  assert(words.length>=20&&words.every((w,i)=>Number.isFinite(w.start)&&w.end>w.start&&w.start>=0&&w.end<=duration+.1&&(!i||w.start>=words[i-1].start)),'Transcript has invalid or unordered word timestamps.');
  const silver=words.find(w=>w.word.toLowerCase()==='silver'),lighthouse=words.find(w=>w.word.toLowerCase()==='lighthouse'),umbrella=words.find(w=>w.word.toLowerCase()==='umbrella');
  assert(silver?.start<1&&lighthouse?.start>2&&lighthouse.start<4&&umbrella?.start>5&&umbrella.start<7,'Anchor timestamps do not match the spoken fixture.');
  assert(sidecar.coverage.transcript.some(r=>r.source_hash===sidecar.technical.file_hash&&r.start_secs===0&&r.end_secs>=duration-.1),'Transcript coverage is stale or incomplete.');
  return sidecar;
}
async function audio(c){await c.setup();const t=await c.timeline('Audio smoke');const placed=await c.place(t,c.assets.plate,0,1,5,{streams:'linked'});return {t,a:placed.find(p=>p.stream==='audio').clip_id};}
function dbClose(actual,expected,label,tolerance=.15){assert(Number.isFinite(actual)&&Math.abs(actual-expected)<tolerance,`${label}: expected ${expected.toFixed(3)} dB, observed ${actual}.`);}
async function effectCheck(c,{type,param,value,neutral,direction}){
  await c.setup();const baseline=await still(c,'baseline');visibleImage(baseline);
  const {scope,node}=await insertEffect(c,type,{[param]:neutral});const identity=await still(c,'neutral');assert(pixelDifference(baseline,identity)<=1,'Neutral grade changes the reference pixels.');
  await c.call('graph.set_param',{...scope,node_id:node.node_id,param,value});
  same((await c.call('graph.get_clip_graph',scope)).nodes.find(n=>n.node_id===node.node_id).params[param],value,'Grade value');
  const changed=await still(c,'changed');assert(pixelDifference(baseline,changed)>1,'Grade edit did not change rendered pixels.');
  if(direction==='brighter')assert(pixelStats(changed).mean>pixelStats(baseline).mean+2,'Positive exposure did not brighten the frame.');
  if(direction==='less-chroma')assert(chroma(changed)<chroma(baseline)*.7,'Reduced saturation did not reduce channel separation.');
  await reopen(c);const persisted=await still(c,'persisted');assert(pixelDifference(changed,persisted)<=1,'Grade changed after reopening.');
  await c.call('graph.set_param',{...scope,node_id:node.node_id,param,value:neutral});const reset=await still(c,'reset');assert(pixelDifference(baseline,reset)<=1,'Reset did not restore reference pixels.');await evidence(c,{baseline,identity,changed,persisted,reset});
  return 'Parameter readback and rendered pixels change as expected, persist through reopening, and reset to the reference.';
}
function chroma(image){let sum=0;for(let i=0;i<image.pixels.length;i+=3)sum+=Math.max(...image.pixels.subarray(i,i+3))-Math.min(...image.pixels.subarray(i,i+3));return sum/(image.pixels.length/3);}
export const extendedCases={
  async 'IN-06'(c){await speech(c);return 'Offline speech ingest produced the expected phrases, ordered word times and current source-linked transcript coverage.';},
  async 'SS-01'(c){await speech(c,{video:true});const result=await search(c,'silver camera',{sources:['transcript'],include:['excerpt']});await writeJSON(path.join(path.dirname(c.bundle),'search.json'),result);assert(result.matches.length>0&&result.matches.every(m=>m.item_id===c.assets.speech),'Transcript search returned the wrong asset.');const hit=result.matches[0],e=hit.evidence.find(e=>e.source==='transcript');assert(hit.range&&e?.retrieval.some(r=>r.lane==='transcript_lexical'&&r.tier==='phrase')&&e.seek_precision==='word','Transcript hit has no word-precise lexical phrase evidence.');assert(e.match_range.start_secs>=0&&e.match_range.start_secs<.5&&e.match_range.end_secs>.8&&e.match_range.end_secs<1.5,'Search word range does not match the known phrase.');assert(Math.abs(hit.range.seek.value/hit.range.seek.rate-e.match_range.seek_secs)<1/24,'Search seek target disagrees with transcript evidence.');return 'A phrase absent from the filename is found in the ingested speech asset with transcript evidence and a source range.';},
  async 'SS-03'(c){await media(c);const result=await search(c,'motion_25');same(result.matches.map(m=>m.item_id),[c.assets.motion],'Filename result identities');assert(result.matches[0].evidence.every(e=>e.source==='name'),'Filename-only search used another source.');return 'Filename-only search returns exactly the intended asset without model-based search.';},
  async 'SS-04'(c){await media(c);assert((await search(c,'motion_25')).matches.length===1,'Positive search control failed.');same((await search(c,'absent_zephyr_8675309')).matches,[],'Absent filename results');return 'An exhaustive name search finds its positive control and returns zero matches for an absent token.';},
  async 'SS-05'(c){await c.create();await c.call('media.add_media_root',{path:c.mediaRoot});const pid=c.engine.child.pid;const before=await c.call('search.query',{query:{kind:'text',text:'silver camera'},sources:['transcript'],include:['excerpt']});assert(before.matches.length===0&&before.source_runs.some(r=>r.error?.code==='search_index_missing'),'Expected explicit missing-index state before ingest.');await c.import('speechVideo');await ingestAssets(c.engine,c.bundle,[{asset_id:c.assets.speechVideo,media_path:path.join(c.mediaRoot,'comet_report.mov')}],{speech:true});const after=await search(c,'silver camera',{sources:['transcript'],include:['excerpt']});assert(c.engine.child.pid===pid&&after.matches.some(m=>m.item_id===c.assets.speechVideo),'New transcript is not searchable in the same engine process.');await writeJSON(path.join(path.dirname(c.bundle),'search-transition.json'),{pid,before,after});return 'An explicit missing-index state becomes a ready, searchable transcript after video ingest without restarting the engine. The project registry is refreshed after ingest.';},
  async 'A-SS-07'(c){await c.setup();const result=await search(c,'motion_25');same(result.matches.map(m=>m.item_id),[c.assets.motion],'Project-wide asset identity');const other=await search(c,'motion_25',{scope:{kind:'assets',asset_ids:[c.assets.plate]}});same(other.matches,[],'Explicit excluded-asset scope');const bin=await c.call('bins.create',{name:'Search subset'});await c.call('bins.set_item_bin',{kind:'asset',item_id:c.assets.motion,bin_id:bin.bin_id});same((await search(c,'motion_25',{scope:{kind:'bin',bin_id:bin.bin_id}})).matches.map(m=>m.item_id),[c.assets.motion],'Bin search');return 'Project, explicit-asset and bin scopes return exactly their eligible media. GUI timeline focus remains manual.';},
  async 'A-IN-07-B'(c){await media(c);const parent=await c.call('bins.create',{name:'Smoke folder'}),child=await c.call('bins.create',{name:'Nested',parent_id:parent.bin_id});assert(parent.bin_id!==child.bin_id,'Bins share identity.');await c.call('bins.rename',{bin_id:child.bin_id,name:'Renamed'});await c.call('bins.set_item_bin',{kind:'asset',item_id:c.assets.motion,bin_id:child.bin_id});await reopen(c);let listed=await c.call('bins.list');assert(listed.bins.some(b=>b.bin_id===child.bin_id&&b.name==='Renamed'&&b.parent_id===parent.bin_id),'Renamed nested bin did not persist.');same((await search(c,'motion_25',{scope:{kind:'bin',bin_id:child.bin_id,recursive:false}})).matches.map(m=>m.item_id),[c.assets.motion],'Child bin search');same((await search(c,'motion_25',{scope:{kind:'bin',bin_id:parent.bin_id,recursive:false}})).matches,[],'Nonrecursive parent search');await c.call('bins.move',{bin_id:child.bin_id,parent_id:'root'});await c.call('bins.set_item_bin',{kind:'asset',item_id:c.assets.motion,bin_id:'root'});await c.call('bins.delete',{bin_id:child.bin_id});await c.call('bins.delete',{bin_id:parent.bin_id});same((await c.call('bins.list')).bins,[],'Removed folders');assert((await c.call('media.resolve_path',{asset_id:c.assets.motion})).path.endsWith('motion_25.mp4'),'Removing folders lost the asset.');return 'Nested folder creation, rename, placement, scope, reopen, move and empty-folder deletion preserve the media identity.';},
  async 'A-IN-07-D'(c){await c.setup();const baseline=snapshotState(await c.inspect(c.main)),pixels=await still(c,'before-delete');await c.call('bins.delete_item',{asset_id:c.assets.plate});same((await search(c,'pattern_24')).matches,[],'Soft-deleted source search');same(snapshotState(await c.inspect(c.main)),baseline,'Placed clips after bin delete');const deleted=await still(c,'after-delete');assert(pixelDifference(pixels,deleted)<=1,'Soft-deleting a bin asset broke a placed clip.');await c.call('bins.restore_item',{asset_id:c.assets.plate});same((await search(c,'pattern_24')).matches.map(m=>m.item_id),[c.assets.plate],'Restored source identity');await reopen(c);assert(pixelDifference(pixels,await still(c,'restored'))<=1,'Restored asset changed timeline render.');return 'Bin soft-delete hides search results while placed clips keep rendering; restore returns the same identity.';},
  async 'A-UI-04'(c){
    const description=c.engine.schema.operations['documents.rename'].properties.name.description;
    const pathIdentity=description==='New document filename stem (moves the file and changes its path and identity)';
    assert(pathIdentity||description==='New document name (user-facing only; the file path is stable)','Unreviewed document rename semantics.');
    await c.create();
    const markdown='# Smoke notes\n\n**Golden project** and [reference](https://example.invalid/smoke).\n';
    const verify=async(doc,text)=>{
      assert(typeof doc.document_id==='string'&&doc.document_id.length>0&&typeof doc.relative_path==='string'&&!path.isAbsolute(doc.relative_path),'Invalid document identity/path.');
      const file=path.resolve(c.bundle,doc.relative_path);
      assert(inside(c.bundle,file)&&inside(await realpath(c.bundle),await realpath(file)),'Document path escapes bundle.');
      if(pathIdentity)same(doc.document_id,doc.relative_path,'Path-based document identity');
      const contents=await readFile(file,'utf8');if(text!==undefined)same(contents,text,'Saved document contents');return contents;
    };
    const absent=async(relative,label)=>{try{await lstat(path.join(c.bundle,relative));assert(false,label);}catch(e){if(e.code!=='ENOENT')throw e;}};
    await reopen(c);
    const baseline=await c.call('documents.list'),contents=new Map();
    for(const doc of baseline.documents)contents.set(doc.document_id,await verify(doc));
    const verifyBaseline=async(documents)=>{for(const doc of baseline.documents){same(documents.find(d=>d.document_id===doc.document_id),doc,'Existing document identity');await verify(doc,contents.get(doc.document_id));}};
    const created=await c.call('documents.create',{name:'Smoke notes',markdown});
    const source=path.join(path.dirname(c.bundle),'import.md'),importedText=markdown+'\nImported copy.\n';
    await writeFile(source,importedText);
    const imported=await c.call('documents.import',{path:source,name:'Imported notes'});
    assert(created.document_id!==imported.document_id&&created.relative_path!==imported.relative_path,'Document import reused the original identity/path.');
    await verify(created,markdown);await verify(imported,importedText);
    await c.call('documents.rename',{document_id:created.document_id,name:'renamed-notes'});
    await reopen(c);
    const listed=await c.call('documents.list');same(listed.documents.length,baseline.documents.length+2,'Documents after rename/reopen');await verifyBaseline(listed.documents);
    const matches=listed.documents.filter(d=>d.name==='renamed-notes');same(matches.length,1,'Renamed document count');const renamed=matches[0];
    if(pathIdentity){
      same(renamed.relative_path,path.posix.join(path.posix.dirname(created.relative_path),'renamed-notes.md'),'Renamed file path');
      assert(renamed.document_id!==created.document_id&&!listed.documents.some(d=>d.document_id===created.document_id),'Rename retained the old document identity.');
      await absent(created.relative_path,'Rename retained the old document file.');
    }else{
      same(renamed.document_id,created.document_id,'Stable document identity after rename');
      same(renamed.relative_path,created.relative_path,'Stable file path after rename');
    }
    await verify(renamed,markdown);
    const retainedImport=listed.documents.filter(d=>d.document_id===imported.document_id);same(retainedImport.length,1,'Imported document after rename');
    same(retainedImport[0].relative_path,imported.relative_path,'Imported document path');await verify(retainedImport[0],importedText);
    await c.call('documents.delete',{document_id:imported.document_id});
    const afterDelete=await c.call('documents.list');same(afterDelete.documents.filter(d=>!contents.has(d.document_id)),[renamed],'Delete removed the wrong document');same(afterDelete.documents.length,baseline.documents.length+1,'Delete removed the wrong document');await verifyBaseline(afterDelete.documents);
    await verify(renamed,markdown);await absent(imported.relative_path,'Deleted document file remains.');
    same(await readFile(source,'utf8'),importedText,'Import source after deletion');
    await writeJSON(path.join(path.dirname(c.bundle),'document-lifecycle.json'),{pathIdentity,baseline,created,imported,afterReopen:listed,afterDelete});
    return 'Markdown create/import contents, independent identities, rename, reopen and targeted delete are verified. Rich editor/chips remain manual.';
  },
  async 'A-AU-01'(c){const {t}=await audio(c),base=await mixReport(c,t,'baseline');const target={timeline_id:t.id,track_id:t.audio};await c.call('audio.set_track',{...target,gain_db:-6});dbClose((await mixReport(c,t,'minus-six')).master.rms_db,base.master.rms_db-6,'Track attenuation');await c.call('audio.set_track',{...target,gain_db:0,mute:true});assert((await mixReport(c,t,'muted')).master.peak_db< -90,'Muted track still emits sound.');await c.call('audio.set_track',{...target,mute:false,solo:true});dbClose((await mixReport(c,t,'solo')).master.rms_db,base.master.rms_db,'Solo level');await c.call('audio.set_track',{...target,solo:false});await c.call('timeline.manage_tracks',{id:'empty-audio',timeline_id:t.id,edits:[{id:'empty',action:'add',kind:'audio',name:'Empty solo control'}]});const empty=(await c.inspect(t)).tracks.find(track=>track.name==='Empty solo control');assert(empty,'Empty solo control track is absent.');await c.call('audio.set_track',{timeline_id:t.id,track_id:empty.track_id,solo:true});assert((await mixReport(c,t,'empty-track-solo')).master.peak_db< -90,'Soloing the empty track did not suppress the populated track.');await c.call('audio.set_track',{timeline_id:t.id,track_id:empty.track_id,solo:false});await reopen(c);dbClose((await mixReport(c,t,'restored')).master.rms_db,base.master.rms_db,'Restored level');return 'Rendered audio follows -6 dB gain, mute, solo and restored mixer state after reopening.';},
  async 'A-AU-01-C'(c){const {t,a}=await audio(c),base=await mixReport(c,t,'baseline');await c.call('audio.set_clip_gain',{timeline_id:t.id,clip_id:a,gain_db:-12});dbClose((await mixReport(c,t,'clip-minus-twelve')).master.rms_db,base.master.rms_db-12,'Clip attenuation');assert((await c.call('undo.undo')).moved,'Clip gain undo was a no-op.');dbClose((await mixReport(c,t,'undo')).master.rms_db,base.master.rms_db,'Undo clip gain');return 'Clip gain changes rendered loudness by -12 dB and undo restores the original audio.';},
  async 'A-AU-01-EQ'(c){const {t}=await audio(c),base=await mixReport(c,t,'baseline');const target={timeline_id:t.id,track_id:t.audio};await c.call('audio.set_eq',{...target,bypassed:false,bands:[{band:0,enabled:true,type:0,freq_hz:440,gain_db:-18,q:1}]});const changed=await mixReport(c,t,'equalized');assert(changed.master.rms_db<base.master.rms_db-10,'A 440 Hz notch did not attenuate the 440 Hz fixture.');await c.call('audio.set_eq',{...target,bypassed:true});dbClose((await mixReport(c,t,'bypassed')).master.rms_db,base.master.rms_db,'EQ bypass');return 'Native EQ attenuates the known tone by more than 10 dB, and bypass restores its rendered level.';},
  async 'A-AU-03'(c){const {t}=await audio(c),r=await mixReport(c,t,'analysis');dbClose(r.master.rms_db,-24.086,'Known fixture RMS',.3);dbClose(r.master.peak_db,-21.073,'Known fixture peak',.3);assert(Number.isFinite(r.master.integrated_lufs),'Integrated loudness is absent.');return 'Four seconds of known stereo audio render to exactly 192,000 samples with expected RMS, peak and finite integrated loudness. Live meters remain manual.';},
  'A-CO-01':c=>effectCheck(c,{type:'wiz.color.grading_primary',param:'grade.primary.saturation',neutral:1,value:0,direction:'less-chroma'}),
  'A-CO-02':c=>effectCheck(c,{type:'wiz.color.grading_tone',param:'grade.tone.scontrast',neutral:1,value:1.5}),
  'A-CO-04':c=>effectCheck(c,{type:'wiz.color.balance_group',param:'balance.grade.exposure_contrast.exposure',neutral:0,value:1,direction:'brighter'}),
  async 'UP-03'(c){await c.setup();const setting=await c.call('color.get_working_space'),before=await still(c,'before');await c.call('color.set_working_space',{working_space:'ACEScg',on_inherit_grades:'preserve'});same((await c.call('color.get_working_space')).working_space,'ACEScg','Changed working space');visibleImage(await still(c,'changed-space'));assert((await c.call('undo.undo')).moved,'Working space undo was a no-op.');same(await c.call('color.get_working_space'),setting,'Undone working space');const undone=await still(c,'undone');assert(pixelDifference(before,undone)<=1,'Working space undo did not restore reference pixels.');await evidence(c,{before,undone});return 'Switching to ACEScg is accepted and renders; one undo restores the exact prior setting and reference pixels.';},
  async 'RG-03'(c){await c.setup();const scope={timeline_id:c.main.id,clip_id:c.a},initial=await c.call('graph.get_clip_graph',scope),baseline=await still(c,'baseline');const composite=initial.nodes.find(n=>n.type==='composite'),edge=initial.edges.find(e=>e.to_node===composite.node_id);await c.call('graph.add_pass',{...scope,type:'rectangle',params:{size:.75,scale_x:.5,pan:.25}});await c.call('graph.add_pass',{...scope,type:'apply_matte'});const prepared=await c.call('graph.get_clip_graph',scope),shapeId=prepared.nodes.find(n=>n.type==='rectangle').node_id,matteId=prepared.nodes.find(n=>n.type==='apply_matte').node_id;await c.call('graph.edit_batch',{...scope,ops:[{op:'disconnect_edge',...edge},{op:'connect_edge',from_node:edge.from_node,from_slot:edge.from_slot,to_node:matteId,to_slot:'image',type:'pixel'},{op:'connect_edge',from_node:shapeId,from_slot:'coverage',to_node:matteId,to_slot:'matte',type:'pixel'},{op:'connect_edge',from_node:matteId,from_slot:'output',to_node:edge.to_node,to_slot:edge.to_slot,type:'pixel'}]});const graph=await c.call('graph.get_clip_graph',scope),mask=graph.nodes.find(n=>n.type==='rectangle'),apply=graph.nodes.find(n=>n.type==='apply_matte');assert(mask&&apply&&graph.edges.some(e=>e.from_node===mask.node_id&&e.to_node===apply.node_id&&e.to_slot==='matte'),'Matte graph connection is missing.');const masked=await still(c,'masked');let retained=0,black=0,count=0;for(let y=100;y<980;y+=20)for(let x=50;x<850;x+=20){const left=(y*1920+x)*3,right=(y*1920+x+1000)*3;for(let k=0;k<3;k++){retained+=Math.abs(masked.pixels[left+k]-baseline.pixels[left+k]);black=Math.max(black,masked.pixels[right+k]);count++;}}assert(retained/count<=1&&black<=1,'Matte does not preserve the left region and black out the right region.');assert((await c.call('undo.undo')).moved,'Matte batch undo was a no-op.');const restored=await still(c,'undone');assert(pixelDifference(baseline,restored)<=1,'Undo did not restore unmasked pixels.');await evidence(c,{baseline,masked,restored});return 'A procedural half-frame matte retains source pixels on the left, blacks out the right, and one undo restores the unmasked frame.';},
  async 'A-RG-04'(c){await c.setup();const baseline=await still(c,'baseline'),blur=await insertEffect(c,'gaussian_blur',{radius:16});const blurred=await still(c,'blurred'),grade=await insertEffect(c,'wiz.color.exposure_contrast',{'grade.exposure_contrast.exposure':1});const both=await still(c,'both');assert(pixelStats(blurred).edgeEnergy<pixelStats(baseline).edgeEnergy*.98,'Blur has no effect.');assert(pixelStats(both).mean>pixelStats(blurred).mean+2,'Exposure does not cooperate with blur.');await c.call('graph.set_bypass',{...grade.scope,node_id:grade.node.node_id,bypassed:true});assert(pixelDifference(blurred,await still(c,'grade-bypassed'))<=1,'Bypassing grade did not retain the blur.');await c.call('graph.set_bypass',{...blur.scope,node_id:blur.node.node_id,bypassed:true});assert(pixelDifference(baseline,await still(c,'both-bypassed'))<=1,'Bypassing both effects did not restore the source.');await evidence(c,{baseline,blurred,both});return 'Chained blur and exposure both affect pixels; bypassing one preserves the other, and bypassing both restores the reference.';},
  async 'A-TL-04-D'(c){await c.setup();const source=snapshotState(await c.inspect(c.main));const result=await c.call('timeline.duplicate',{source_timeline_id:c.main.id,name:'Independent copy'});const t={id:result.timeline_id,fps:24};const copy=await c.inspect(t);t.video=copy.tracks.find(t=>t.address==='V1').track_id;t.audio=copy.tracks.find(t=>t.address==='A1').track_id;const copied=clips(copy);same(copied.map(i=>[i.source.asset_id,i.timeline_range,i.source.source_range]),clips(source).map(i=>[i.source.asset_id,i.timeline_range,i.source.source_range]),'Duplicated content');assert(copied.every(i=>!clips(source).some(s=>s.clip_id===i.clip_id)),'Duplicate reused source clip identities.');await c.move(t,[copied[0].clip_id],t,1,{ripple:{source:false,destination:false}});same(snapshotState(await c.inspect(c.main)),source,'Original after copy edit');bounds(clip(await c.inspect(t),copied[0].clip_id),1,5,1,5);await reopen(c);same(snapshotState(await c.inspect(c.main)),source,'Original after reopening');return 'Timeline duplication copies source ranges into independent clip identities; editing the copy leaves the original unchanged.';},
  async 'A-TL-03-R'(c){await c.setup();await c.call('timeline.retime_clips',{id:'double-speed',timeline_id:c.main.id,edits:[{id:'a',clip:{clip_id:c.a},speed:2}],ripple:false,streams:'video_only'});const s=await c.inspect(c.main);bounds(clip(s,c.a),0,2,1,5);bounds(clip(s,c.b),6,8,0,2);assert((await c.call('undo.undo')).moved,'Retime undo was a no-op.');bounds(clip(await c.inspect(c.main),c.a),0,4,1,5);return 'Double speed halves the timeline duration while preserving the source window and following content; undo restores timing.';},
  async 'A-LP-02-S'(c){await c.setup();const original=c.bundle,before=await c.both(),destination=path.join(path.dirname(original),'Saved-copy.wiz');await c.call('project.save_as',{destination});c.bundle=destination;await c.call('project.open');same(await c.both(),before,'Saved-as project');await c.move(c.main,[c.a],c.main,1,{ripple:{source:false,destination:false}});await c.call('project.checkpoint');c.bundle=original;await c.call('project.open');same(await c.both(),before,'Original after saved-copy edit');return 'Save As preserves the populated project and subsequent edits to the copy leave the original unchanged.';}
};
