import path from 'node:path';
import {readFile,copyFile,mkdir,rename} from 'node:fs/promises';
import {assert,same,near,clips,clip,bounds,snapshotState} from './engine.mjs';
import {writeJSON} from './files.mjs';
import {ingestAssets,reopen,still,evidence,insertEffect,cloneEffect,placeMany,reference} from './interactions.mjs';
import {pixelStats,pixelDifference,visibleImage} from './pixels.mjs';
const curve=points=>({schema_id:'wiz.color.bspline_curve.v1',schema_version:1,value:{points:points.map(([x,y])=>({x,y}))}});
async function curveCheck(c,type,param,points){
  await c.setup();const before=await still(c,'before'),effect=await insertEffect(c,type);assert(pixelDifference(before,await still(c,'neutral'))<=1,'Neutral curve changes pixels.');
  const value=curve(points);await c.call('graph.set_param',{...effect.scope,node_id:effect.node.node_id,param,value});const changed=await still(c,'changed');assert(pixelDifference(before,changed)>1,'Curve edit did not change pixels.');same((await c.call('graph.get_clip_graph',effect.scope)).nodes.find(n=>n.node_id===effect.node.node_id).params[param],value,'Stored curve');
  await reopen(c);assert(pixelDifference(changed,await still(c,'reopened'))<=1,'Curve changed after reopen.');await c.call('graph.remove_param',{...effect.scope,node_id:effect.node.node_id,param});const reset=await still(c,'reset');assert(pixelDifference(before,reset)<=1,'Removing the curve did not restore the default.');await evidence(c,{before,changed,reset});return 'Explicit curve control points change real rendered pixels, survive reopen and reset to the original image.';
}
async function gradeStack(c,count=6){const nodes=[];for(let i=0;i<count;i++)nodes.push(await insertEffect(c,'wiz.color.exposure_contrast',{'grade.exposure_contrast.exposure':.15}));return nodes;}
export const remainingCases={
  async 'A-IN-04-W'(c){await c.create();await c.call('media.add_media_root',{path:c.mediaRoot});const output=path.join(path.dirname(c.bundle),'tone.f32le');const result=await c.call('media.extract_audio',{path:path.join(c.mediaRoot,'pattern_24.mov'),output,sample_rate:16000,channels:1,in_pts:1,out_pts:3});same(result.buffer.format,{channels:1,encoding:'f32le',frame_count:32000,layout:'planar',sample_rate:16000},'Extracted PCM format');assert(result.buffer.path===output&&result.has_audio,'Audio extraction returned the wrong output.');const bytes=await readFile(output);assert(bytes.length===128000,'Extracted audio has the wrong duration.');let sum=0,peak=0,crossings=0,previous=0;const envelope=[];for(let i=0;i<32000;i++){const x=bytes.readFloatLE(i*4);assert(Number.isFinite(x)&&Math.abs(x)<=1,'Invalid PCM sample.');sum+=x*x;peak=Math.max(peak,Math.abs(x));if(previous<0&&x>=0)crossings++;previous=x;const bucket=Math.floor(i/160);envelope[bucket]=Math.max(envelope[bucket]||0,Math.abs(x));}const rms=Math.sqrt(sum/32000),hz=crossings/2;assert(rms>.04&&rms<.15&&peak>.08&&Math.abs(hz-440)<2,'Decoded audio does not contain the known 440 Hz tone.');await writeJSON(path.join(path.dirname(c.bundle),'waveform.json'),{sampleRate:16000,samples:32000,rms,peak,frequencyHz:hz,envelope});return 'Two seconds decode to 32,000 finite mono samples with the known 440 Hz tone and a nonempty waveform envelope. UI waveform display remains separate.';},
  async 'A-IN-05'(c){await c.setup();const video=await c.call('media.detect_color',{path:path.join(c.mediaRoot,'pattern_24.mov'),default_policy:'per_category'}),stillResult=await c.call('media.detect_color',{path:path.join(c.mediaRoot,'still.png'),category:'still',default_policy:'per_category'});same(video.resolved_name,'Rec.1886 Rec.709 - Display','Video source colour');same(stillResult.resolved_name,'sRGB - Display','Still source colour');assert(video.match_source==='file_rule'&&stillResult.match_source==='file_rule_default'&&video.status==='needs_confirmation'&&stillResult.status==='needs_confirmation','Detection confidence/provenance was lost.');const graph=await c.call('graph.get_clip_graph',{timeline_id:c.main.id,clip_id:c.a});same(graph.nodes.find(n=>n.type==='wiz.color.input_color_space_transform').params['input.cst.src'],video.resolved_name,'Ingested source transform');await writeJSON(path.join(path.dirname(c.bundle),'colour-detection.json'),{video,still:stillResult});return 'Video/still colour rules resolve the expected encodings with honest confirmation status, and the ingested clip uses the detected input transform.';},
  async 'A-IN-08-R'(c){await c.create();const dir=path.join(path.dirname(c.bundle),'source');await mkdir(dir);const file=path.join(dir,'recover.mov'),away=file+'.offline';await copyFile(path.join(c.mediaRoot,'pattern_24.mov'),file);await c.call('media.add_media_root',{path:dir});const asset=await c.import('plate',file);await ingestAssets(c.engine,c.bundle,[{asset_id:asset,media_path:file}]);c.main=await c.timeline('Recovery');c.a=(await c.place(c.main,asset,0,1,5))[0].clip_id;const baseline=snapshotState(await c.inspect(c.main)),before=await still(c,'before');await c.call('project.checkpoint');await c.call('project.close');await rename(file,away);try{await c.call('project.open');same((await c.call('media.resolve_path',{asset_id:asset})).path,file,'Missing source path identity');await c.call('media.probe',{path:file},['probe_failed']);same(snapshotState(await c.inspect(c.main)),baseline,'Timeline with missing source');}finally{await rename(away,file);}await c.call('project.close');await c.call('project.open');assert((await c.call('media.resolve_path',{asset_id:asset})).path===file,'Recovered identity resolved to the wrong path.');const recovered=await still(c,'recovered');assert(pixelDifference(before,recovered)<=1,'Restoring the source did not restore rendered pixels.');return 'Removing a local source is detected without losing timeline references; restoring it at the original path restores pixels. Selecting a different relink path remains separate.';},
  'A-CO-03-R':c=>curveCheck(c,'wiz.color.grading_rgb_curve','grade.curve.master',[[0,0],[.5,.7],[1,1]]),
  'A-CO-03-H':c=>curveCheck(c,'wiz.color.grading_hue_curve','grade.hue_curve.hue_sat',[[0,.3],[.5,.3],[1,.3]]),
  async 'A-CO-04-W'(c){await c.setup();const before=await still(c,'before'),e=await insertEffect(c,'wiz.color.white_balance',{'grade.white_balance.temperature':3500});const warm=await still(c,'warm');assert(pixelDifference(before,warm)>2,'White balance did not change pixels.');await c.call('graph.set_param',{...e.scope,node_id:e.node.node_id,param:'grade.white_balance.temperature',value:6500});assert(pixelDifference(before,await still(c,'neutral'))<=1,'Neutral white balance did not restore the image.');await c.call('graph.set_param',{...e.scope,node_id:e.node.node_id,param:'grade.white_balance.tint',value:20});const tinted=await still(c,'tinted');assert(pixelDifference(before,tinted)>1,'Tint did not change pixels.');await c.call('undo.undo');assert(pixelDifference(before,await still(c,'undone'))<=1,'Tint undo did not restore the image.');await evidence(c,{before,warm,tinted});return 'Temperature and tint each change rendered pixels; neutral temperature and tint undo restore the reference.';},
  async 'A-CO-05'(c){await c.setup();const first=c.main,id=c.a,before=await still(c,'before');const original=await insertEffect(c,'wiz.color.exposure_contrast',{'grade.exposure_contrast.exposure':1});const graded=await still(c,'source-graded'),copy=await c.timeline('Grade copy');const copied=(await c.place(copy,c.assets.plate,0,1,5))[0].clip_id;c.main=copy;c.a=copied;const replica=await cloneEffect(c,original.node.type,original.node.params);assert(pixelDifference(graded,await still(c,'copy-graded'))<=1,'Copied grade differs from source pixels.');await c.call('graph.set_param',{...replica.scope,node_id:replica.node.node_id,param:'grade.exposure_contrast.exposure',value:0});assert(pixelDifference(before,await still(c,'copy-reset'))<=1,'Reset copy did not return to source pixels.');c.main=first;c.a=id;assert(pixelDifference(graded,await still(c,'original-unchanged'))<=1,'Editing the copied grade changed the original.');await reopen(c);assert(pixelDifference(graded,await still(c,'original-reopened'))<=1,'Original grade did not persist.');return 'Recreating a grade from its semantic parameters reproduces pixels on another clip; editing the copy leaves the original unchanged. Clipboard UI remains separate.';},
  async 'A-PF-01'(c){await c.setup();const before=await still(c,'before');const start=performance.now();const nodes=await gradeStack(c),graded=await still(c,'six-grades');const elapsedMs=performance.now()-start;assert(pixelStats(graded).mean>pixelStats(before).mean+5,'Six exposure grades did not brighten the render.');for(const e of nodes)await c.call('graph.set_bypass',{...e.scope,node_id:e.node.node_id,bypassed:true});assert(pixelDifference(before,await still(c,'bypassed'))<=1,'Bypassing six grades failed to restore the reference.');await writeJSON(path.join(path.dirname(c.bundle),'timing.json'),{elapsedMs,measurement:'six grade additions plus one offline still; not real-time playback'});return 'Six connected grades render together and bypass restores the reference; elapsed time is retained. Real-time playback remains separate.';},
  async 'A-PF-03'(c){await c.setup();const t=await c.timeline('Six layers');c.main=t;for(let i=0;i<6;i++){if(i)await c.call('timeline.manage_tracks',{id:'layer-'+i,timeline_id:t.id,edits:[{id:'track',action:'add',kind:'video',name:'Layer '+(i+1)}]});const s=await c.inspect(t),track=s.tracks.find(t=>t.address==='V'+(i+1)).track_id;c.a=(await c.place(t,c.assets.plate,0,1,5,{track}))[0].clip_id;await insertEffect(c,'wiz.color.exposure_contrast',{'grade.exposure_contrast.exposure':i*.15});}const composite=await still(c,'stack');visibleImage(composite);const top=c.a;await c.call('timeline.set_enabled',{id:'hide-top',timeline_id:t.id,target:{clips:[{clip_id:top}]},enabled:false});const lower=await still(c,'five-layers');assert(pixelDifference(composite,lower)>1,'Hiding the top graded layer did not reveal different pixels.');await c.call('undo.undo');assert(pixelDifference(composite,await still(c,'restored'))<=1,'Undo did not restore the top layer.');return 'Six overlapping graded video layers render; hiding the top layer reveals the lower grade and undo restores it. Playback rate remains separate.';},
  async 'A-PB-11'(c){await c.setup();const first=await still(c,'plate-reference',1),second=await still(c,'motion-reference',7);const t=await c.timeline('Twenty cuts');for(let i=0;i<20;i++)await c.place(t,i%2?c.assets.motion:c.assets.plate,i, i%2?.5:1.5,i%2?1.5:2.5);c.main=t;const order=[0,19,1,18,2,17,3,16,4,15,5,14,6,13,7,12,8,11,9,10];for(const i of order){const frame=await still(c,'seek-'+i,i+.5);assert(pixelDifference(frame,i%2?second:first)<=1,`Random access at clip ${i} returned stale/wrong pixels.`);}return 'Twenty alternating clips render the correct source pixels when visited in a back-and-forth order. GUI scrubbing and frame-drop measurement remain separate.';},
  async 'A-PF-15'(c){await c.setup();const timelines=[];for(let i=0;i<20;i++){const t=await c.timeline('Large '+i);await placeMany(c,t,25);timelines.push({t,state:snapshotState(await c.inspect(t))});}await c.call('project.checkpoint');await c.call('project.close');const start=performance.now();await c.call('project.open');const openMs=performance.now()-start;let total=0;for(const {t,state}of timelines){const actual=await c.inspect(t);same(snapshotState(actual),state,'Reopened '+t.id);total+=clips(actual).length;}assert(total===500,'Large fixture lost clips.');await writeJSON(path.join(path.dirname(c.bundle),'timing.json'),{openMs,timelines:20,clips:500,scope:'headless project.open; no UI latency claim'});return `Twenty populated timelines and 500 clips survive reopening with exact identities and timing. Headless open took ${openMs.toFixed(1)} ms; no performance baseline is asserted.`;},
  async 'A-PF-17'(c){await c.setup();const history=[await c.both()],times=[];for(let i=0;i<50;i++){const t=i%2?c.alternate:c.main,id=i%2?c.c:c.a,pos=Math.floor(i/2)%2?0:1;await c.move(t,[id],t,pos);history.push(await c.both());}for(let i=49;i>=0;i--){const start=performance.now();assert((await c.call('undo.undo')).moved,'Undo was a no-op.');times.push(performance.now()-start);same(await c.both(),history[i],'Long-history undo '+i);}for(let i=1;i<=50;i++){assert((await c.call('undo.redo')).moved,'Redo was a no-op.');same(await c.both(),history[i],'Long-history redo '+i);}await writeJSON(path.join(path.dirname(c.bundle),'timing.json'),{undoMs:times,scope:'CLI round-trip timings; no UI responsiveness claim'});return 'Fifty edits, fifty undos and fifty redos reproduce every recorded state across two timelines; operation timings are retained.';},
  async 'A-PF-19'(c){await c.setup();const source=await c.timeline('Bulk source'),destination=await c.timeline('Bulk destination',25);await placeMany(c,source,100);const baseline=snapshotState(await c.inspect(source)),ids=clips(baseline).map(i=>i.clip_id);const start=performance.now();await c.move(source,ids,destination,0,{copy:true,ripple:{destination:false,source:false}});const copyMs=performance.now()-start,actual=await c.inspect(destination),copied=clips(actual).sort((a,b)=>a.timeline_range.start_seconds-b.timeline_range.start_seconds);assert(copied.length===100&&copied.every(i=>!ids.includes(i.clip_id)),'Bulk copy omitted clips or reused identities.');copied.forEach((item,i)=>{bounds(item,i*2,i*2+1,1,2);assert(item.source.asset_id===c.assets.plate,'Copied source changed.');});same(snapshotState(await c.inspect(source)),baseline,'Bulk-copy source');await c.call('undo.undo');assert(clips(await c.inspect(destination)).length===0,'Undo did not remove the bulk copy.');same(snapshotState(await c.inspect(source)),baseline,'Original after undo');await writeJSON(path.join(path.dirname(c.bundle),'timing.json'),{copyMs,clips:100,sourceFps:24,destinationFps:25});return 'One operation copies 100 clips from 24 to 25 fps with exact timing and independent IDs; undo removes only the copies.';}
};
