// Human explanations of the actual check paths; assertions remain in linked source.
export const methods={
'D-CLI-01':'The adapter launches a disposable GUI copy with isolated settings, checks that its endpoint belongs to the launched PID, and inspects the visible window for the expected Golden Project.',
'D-CLI-02':'Rename a timeline through the paired CLI, then read the Qt timeline selector and Media model. The UI observations are independent of the mutation response.',
'D-PB-01':'Bind Main, seek to frame 30, play briefly and pause. Compare successive transport snapshots and the visible timecode, then check that pause holds and a second seek lands correctly.',
'D-LP-02-SAVE':'Read timeline content, trigger the real Save action, and compare the saved project with the observed content. A successful action dispatch alone does not satisfy the check.',
'D-LP-02-RELAUNCH':'Stop the owned app, launch a new process and compare the saved timeline and selected timeline name. The harness opens its designated timeline; this does not prove every previous tab restores.',
'D-MEDIA-VIEWS':'Switch the Media panel between list and grid and compare the displayed fixture items. This tests the two real views, not just an asset listing from the CLI.',
'D-MEDIA-OPEN':'Select the known source in the Media view and open it through the real item interaction. Inspect the resulting editor controls and source duration.',
'D-MEDIA-TIMELINE':'Double-click each known timeline in Media, then confirm the visible selector names the opened timeline. Reuse observed model items rather than fixed screen coordinates.',
'D-TRANSPORT-KEYS':'Send real Qt key events for frame stepping and play/pause to the active timeline. Read transport afterward to distinguish a handled shortcut from a no-op.',
'D-TIMELINE-TOOLS':'Send tool and snapping shortcuts, inspect the selected UI controls, then restore the initial setting so subsequent tests inherit a known editor state.',
'D-EDIT-SPLIT-REDO':'Select the fixture clip, seek to the split point and send the blade shortcut. Inspect the resulting clips, exact source intervals and authority diagnostics; compare undo and redo states.',
'D-EDIT-DELETE':'Select one clip and send Delete. Compare the resulting timeline against the baseline, then undo and require the original content to return.',
'D-EDIT-DISABLE':'Toggle the selected clip through the editor, read its enabled state and undo. The assertion is about that clip; it does not certify every bypass path.',
'D-EDIT-NUDGE':'Select a fixture clip and send the one-frame nudge key. Compare placement, source window and neighboring content, then restore the timeline with undo.',
'D-EDIT-DRAG':'Drag a clip in the default timeline layout with Qt mouse events. Verify frame-aligned placement, unchanged source/duration and unaffected neighbors through timeline inspection.',
'D-EDIT-TRIM':'Drag the clip’s right edge and inspect the new timeline and source intervals. The test also rejects timing-authority diagnostics and checks restoration with undo.',
'D-TRACK-ADD':'Click the observed + Video and + Audio controls, save, then inspect the persisted track list. Verify the track kind and empty contents, then undo.',
'D-PROJECT-CANCEL-CLOSE':'Create an unsaved change and close the owned window. Choose Cancel in the actual prompt, then verify that the app remains alive and the edit remains present.',
'D-MEDIA-SEARCH':'Type a known filename into the visible Media search field and require the expected result. An unavailable search service is recorded as Blocked; clearing the field must restore the list.',
'D-EXPORT-CANCEL':'Open the actual Export dialog, cancel it, and verify that no output was created and the project stayed unchanged.',
'D-EDIT-CLIPBOARD':'Use the editor’s copy/paste shortcuts on a selected clip. Inspect the new identity and its source and placement, then undo and compare the original timeline.',
'D-INSPECTOR-01':'Change Position X through the Inspector, read the graph parameter and render a still. Reset the control and require both the original parameter and pixels to return.',
'D-EXPORT-01':'Fill the real Export dialog for a two-second H.264 movie. Probe and decode the file independently, checking dimensions, frame count, frame rate, duration and audio codec.',
'D-MGFX-01':'Create a synthetic local title through the application’s generation operation. Render it, edit the title parameter, and verify changed pixels without calling a network provider.',
'D-UI-DEFAULT':'Start with fresh isolated preferences and inspect the expected default panels and editor controls. This checks their presence; subjective layout quality remains a human judgment.',
'D-UI-PREFERENCES':'Open Preferences and navigate the Application and Current Project pages. Inspect their controls, cancel, and require the project to remain unchanged.',
'D-PREVIEW-FULLSCREEN':'Enter fullscreen preview, exercise its play/pause controls, observe transport and then press Escape. Verify restoration of the ordinary preview.',
'D-SELECT-ALL':'Use Select All and Delete on a known timeline, inspect that every intended clip is removed, then require one undo to restore the baseline.',
'D-CUT-PASTE':'Use the real cut/paste keys with an owned clipboard preservation step. Verify source and placement in the moved material and restore the timeline with two undos.',
'D-SHORTCUT-REBIND':'Assign a temporary play/pause shortcut through Preferences, exercise it, reset that command and exercise its original Space binding. Restore the prior settings.',
'D-SB-CREATE':'Open Spellbook, create a Spell with its keyboard shortcut and another with the corner plus button. Compare native document IDs and visible tabs to prove independent creation.',
'D-SB-GRAPH':'Author a source and two effects through spellbook.edit_batch. Connect, disconnect and reconnect their native edges, checking graph structure after each operation. This fixture does not itself claim rendered output.',
'D-SB-PARAMS':'Set a blur radius through the native Spellbook edit API, then inspect that node’s effective control value. Inspector gestures and canvas output are separate checks.',
'D-SB-BYPASS':'Use application-owned edits to bypass and re-enable a node. Read its native state after each change; this does not substitute for the D shortcut or a pixel comparison.',
'D-SB-UNDO':'Commit multiple Spell edits in one batch, then send actual undo and redo keys to the canvas. Compare complete graph content before, after and after restoration.',
'D-SB-ATOMIC':'Submit a batch containing a valid rename followed by an invalid edge. Require the specific rejection and compare the full document to prove that the rename did not partially commit.',
'D-SB-STALE':'Capture a document fingerprint, make a newer edit, then try to write with the old fingerprint. Require stale_document and unchanged current content.',
'D-SB-INSTANCE':'Expose a blur input, instantiate the definition with another value, and edit the instance again. Inspect both owners to prove independent values and preserved definition identity.',
'D-SB-PERSIST':'Save authored definitions and instances, terminate the app and inspect them in a new process. Compare graphs, public inputs and native parameters with retained expectations.',
'D-SB-QUICK-SEARCH':'Open Quick Node Search with its shortcut, search for Text and double-click the real result. Require a new native Text node, then one undo restoring the graph.',
'D-CROSSRATE-CLIPBOARD':'Copy through the GUI from a 24 fps timeline and paste into a 25 fps timeline. Check independent clip identity, exact source time and destination placement; undo restores the target.',
'D-PLAYBACK-SWITCH':'Open a secondary timeline, play and observe transport, then switch to Main and seek. Confirm the selected timeline and timecode; seamless output continuity is a separate question.',
'D-SCOPES-01':'Capture the real scope widgets on a video frame and a black gap at each supported tap. Compare the plotted pixels so an unchanged or frozen scope cannot pass.',
'D-SB-LOGGING':'Enable verbose project-local logging in Preferences, reconstruct a Spell and inspect the visible console for native debug messages. Restore the earlier preference afterward.',
'D-COMPOUND-CREATE':'Select a clip and press Command+G. Inspect the new child timeline reference, source and placement, and compare rendered pixels with the original.',
'D-COMPOUND-EDIT':'Open the converted child from Media, disable its clip and render the parent to observe the effect. Undo must restore the parent’s original pixels.',
'D-MGFX-CLIPBOARD':'Copy and paste an MGFX placement with actual keyboard routing. Inspect the new generation identity, change the copy’s parameters and prove only its values and pixels change.',
'D-EXPORT-COMPOUND':'Prepare local graphics and converted media in one timeline, export with the real dialog, then decode frames from both segments and check the 96-frame movie.',
'D-COMPOUND-DISSOLVE':'Use Command+Shift+G on the converted reference. Compare resulting media placements and rendered pixels, then require one undo to restore the reference.',
'D-EXPORT-STILL':'Choose Still at Playhead in the real Export dialog. Decode the JPEG and compare it with the expected image at the selected playhead time.',
'D-LINKED-SELECTION':'Toggle Linked Selection and nudge selected video in both states. Timeline snapshots must show both streams moving when enabled and video alone when disabled; undo restores both.',
'D-TRACK-LOCK-UI':'Click the visible track padlock and attempt blade and drag edits. Verify that locked content is unchanged, then unlock, move the clip and undo.',
'D-TRACK-TARGETING':'Use the V1/A1 target badges, then Select All/Delete. Compare exactly which tracks lost clips; untargeted clips must remain byte-for-byte equivalent in the normalized snapshot.',
'D-RIPPLE-GAP':'Select the two-second gap and send Shift+Delete. Verify that later content moves from six seconds to four, with its source unchanged, then undo.',
'D-BIN-RENAME':'Rename a known asset through the bin menu. Check saved display name, original identity, source bytes and rendered placements, restore its name, then verify after reopening.',
'D-BIN-DUPLICATE':'Duplicate a source through the bin menu and rename the copy. Check separate IDs and unchanged original data; a later fresh-process check also requires both correct visible names.',
'D-BIN-DELETE':'Delete an asset from the bin while it remains placed in a timeline. Verify the source file and placement still render, then undo and inspect the restored asset after reopen.',
'D-BIN-MGFX':'Duplicate the generated item through the actual bin menu. Find the copied generation, edit only its text, compare both images and values, and reopen to check persistence.',
'D-EDIT-SLIP':'Drag inside a clip with the Slip tool. Inspect source timing while requiring placement and duration to remain unchanged; reject invalid exact authority and undo.',
'D-LINK-UNLINK-UI':'Use the Link/Unlink shortcut and nudge the selected video. Compare group membership and stream motion before and after relinking, then undo.',
'D-BLADE-NO-SELECTION':'With nothing selected, invoke blade at the playhead. Require both streams to split at contiguous source boundaries with valid timing authority, then undo.',
'D-FRACTIONAL-CLIPBOARD':'Copy 24 frames at 24000/1001 through the GUI and paste into a 30000/1001 timeline. Verify independent identity and the exact rational-rate placement and source time.',
'D-TIMELINE-TABS':'Set zoom and a nonzero horizontal scroll, save and close the tab, then reopen it from Media. Compare both viewport values and timeline content.',
'D-SAVE-DISCARD':'Save and close cleanly, reopen in a new process, make another edit and choose Don’t Save in the close prompt. A third process must restore the saved version.',
'D-NODE-CLIPBOARD-BYPASS':'Use Copy/Paste Nodes on two clips, verify independent node IDs and matching pixels, then edit the copy. Use D on the selected render node and the grade-panel bypass, checking images for both off and on states.',
'D-DOCUMENT-EDIT':'Apply bold and a link through keyboard shortcuts, type an @ mention and select a result. Compare saved Markdown and reopened rich text. The mention registry is the build’s fixture registry, not live project-item resolution.',
'D-PREVIEW-SCRUB':'Drag the real scrubber to video and gap positions. Capture only the owned Wizard window, then independently seek to the observed frame and compare preview pixels. Allow one-frame pointer quantization.',
'D-PLAYBACK-INOUT':'Use I and O at known times, verify the mark indicators, navigate with Shift+I/O and clear with Alt+X. The Out value is the exclusive boundary after the marked frame.',
'D-PLAYBACK-LOOP':'Inspect visible controls and playback operations for an application-owned loop function. None is exposed in this build, so the script records Blocked; it does not fake looping with repeated seeks.',
'D-SCRUB-CUTS':'Build twenty one-second cuts alternating colour and grayscale. Drag the scrubber backward and forward across distant cuts and measure preview brightness and chroma to detect stale or black frames.',
'D-SB-TAB-RENAME':'Create a Spell, rename it through the tab menu, author retained text, save and close the tab. Reopen it from Media and compare content; inspect the same document again in a fresh process.',
'D-SB-TAB-DUPLICATE':'Inspect the actual Spell tab menu for duplication. No duplicate-tab action is present. Instantiation is tested separately and does not satisfy this user path.',
'D-SB-SEARCH-DROP':'Search for Text, ask the application’s result model for its actual MIME payload and deliver Qt drag/drop events to the canvas. Require native node creation and one-step undo. This is not an OS pointer-drag test.',
'D-SB-INSPECTOR-PREVIEW':'Bind a local still to a source/blur graph and use the app render command to establish a preview. Drag the Inspector slider, require the actual canvas thumbnail pixels to change without another render command, then Undo and require the original pixels. Provider graphs are rejected.',
'D-MEDIA-RELINK':'Move a disposable source and restart to refresh offline availability. Use the real Locate/Relink folder dialog and Save; compare live and saved paths, identity, source hash and rendered pixels, then restart and compare again.',
'D-CURVE-RGB-CLIPBOARD':'Drag a Master curve point in the unified Curves panel and compare graph points and rendered pixels. Copy/paste the curve to another clip, double-click reset the copy and verify the original remains edited.',
'D-CURVE-HUE-RESET':'Expand the Hue group, select Hue Shift and drag a curve point. Check native curve points and changed rendered pixels, then double-click reset and require neutral pixels.',
'S-MGFX-DUPLICATE-DEFAULT':'Call the real generation-duplicate operation on a local title whose optional group label was omitted. Require valid independent generation state; this is the retained descriptor failure.',
'S-MGFX-DUPLICATE':'Create a local title with an explicit group label, duplicate its generation and edit the copy. Compare original and copied parameter values and rendered images.',
'S-MGFX-CLIP-COPY':'Duplicate a placed generation through the application service API, inspect independent placement/generation IDs, edit the copy and verify only its rendered segment changes. Keyboard routing is separate.',
'S-MGFX-UNDO-PUBLISH':'Publish local graphics, undo the placement and redo it. Require restored timeline identities and pixels; this does not classify retained undo assets as orphan files.',
'S-MGFX-PERSIST':'Restart the owned app and inspect both generated owners and timelines. Render the retained copied timeline and compare with the saved reference image.',
'S-EXPORT-PRORES':'Ask Wizard’s export worker to prepare a ProRes request, export 48 frames, then independently probe/decode the movie. Check stream format, duration, PCM audio and nonblank image content.',
'S-EXPORT-AV1':'Use the actual Wizard export worker for a two-second AV1 movie. Check all 48 frames were written, probe codec/rate/dimensions and AAC audio, and decode a nonblank image.',
'S-EXPORT-UNSET-RATE':'Create a genuine empty unset-rate project through New Project, change only its raster, and stop the app. Require the export worker to resolve 24 fps and write 48 black H.264 frames without rewriting the timeline; probe/decode independently. Restore the original project. This uses the foreground desktop lane and does not cover populated unset-rate timelines.'
};
